### ISSUE TITLE
Errors deploying

### ISSUE THREAD

**Issue by rstratf4** [cloudfoundry-incubator/bosh-azure-cpi-release#101]
We were trying to do a stemcell roll and encountered the following errors:

Started compiling packages > switchboard/941dfdd61e92f3f45af7a95df6b8aa33fba2e661
   Failed compiling packages > golang1.3/e4b65bcb478d9bea1f9c92042346539713551a4a: status: Failed
http code: 200
request id: b34bda50-c66e-46d2-838c-cd4e533ed56c
error:
{"code"=>"NetworkingInternalOperationError", "message"=>"Unknown network allocation error."}
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:924:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:976:in `http_put'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:187:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:89:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:90:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3100.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:83:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:71:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:71:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:34:in `<main>' (00:02:25)

Error 100: status: Failed
http code: 200
request id: b34bda50-c66e-46d2-838c-cd4e533ed56c
error:
{"code"=>"NetworkingInternalOperationError", "message"=>"Unknown network allocation error."}
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:924:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:976:in `http_put'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:187:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:89:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:90:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3100.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:83:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:71:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:71:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:34:in `<main>'

Task 1110 error

**Comment by AbelHu** [comment]
@rstratf4 Please file a ticket in Azure portal for this error. After you file the ticket, Azure support guys can help you to collect logs and investigate the root cause.

Simply select “Support” from the menu bar or open the “Help + support” hub.
![image](https://cloud.githubusercontent.com/assets/6416187/13589273/935789d0-e511-11e5-829d-63a7b48e6dd0.png)

**Comment by AbelHu** [comment]
@rstratf4 Do you have any progress?

**Comment by rstratf4** [comment]
I was training with someone.  I believe they resolved the issue.  Thanks
