### ISSUE TITLE
Not found manifest files

### ISSUE THREAD

**Issue by b10-dbqg** [cloudfoundry-incubator/bosh-azure-cpi-release#104]
I'd like to download multiple-vm-cf.yml but page is Not found.
https://raw.githubusercontent.com/Azure/azure-quickstart-templates/abelhu/bosh-setup/manifests/multiple-vm-cf.yml

(single-vm-cf.yml is same)

**Comment by AbelHu** [comment]
@b10-dbqg Wrong links. I will fix it soon. You can download them from 
https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/bosh-setup/manifests/multiple-vm-cf.yml
https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/bosh-setup/manifests/single-vm-cf.yml

**Comment by b10-dbqg** [comment]
@AbelHu Thanks.
