### ISSUE TITLE
Merge readme with bosh.io docs

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#115]
https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/src/bosh_azure_cpi contains duplicate information as bosh.io/docs/azure-cpi.html. i think it makes sense to add missing info to cloudfoundry/docs-bosh repo (which is source for bosh.io docs) and remove this readme file. wdyt?

**Comment by cppforlife** [comment]
ping @AbelHu

**Comment by cppforlife** [comment]
@AbelHu i merged changes into docs-bosh. any other info we need to move there before we remove readme details out of this repo?

**Comment by AbelHu** [comment]
PR https://github.com/cloudfoundry/docs-bosh/pull/116 is created. After this PR is merged, README.md can be deleted.

**Comment by AbelHu** [comment]
Will close this after http://bosh.io/docs/azure-cpi.html is updated.

**Comment by cppforlife** [comment]
This was merged some time ago into bosh.io docs. Let's delete https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/src/bosh_azure_cpi/README.md

**Comment by AbelHu** [comment]
Done
