### ISSUE TITLE
Unknown CPI "'Bosh::AzureCloud::AzureError' " error  encountered during Bosh Deployment 

### ISSUE THREAD

**Issue by cwackro** [cloudfoundry-incubator/bosh-azure-cpi-release#118]
During our Bosh deployment in azure we encountered the following error message :
. 
Failed: Unknown CPI error 'Bosh::AzureCloud::AzureError' with message 'status: Failed
http code: 200
request id: 2fd005bc-c0fd-496a-bfef-6e65d5e56d73
error:
{"code"=>"InternalExecutionError", "message"=>"An internal execution error occurred."}' (00:01:34)

Error 100: Unknown CPI error 'Bosh::AzureCloud::AzureError' with message 'status: Failed
http code: 200
request id: 2fd005bc-c0fd-496a-bfef-6e65d5e56d73
error:
{"code"=>"InternalExecutionError", "message"=>"An internal execution error occurred."}'

We can provide additional log files in a non public forum.

Thanks!

**Comment by AbelHu** [comment]
@cwackro Which CPI version are you using? Could you send the task logs to me chou.hu@microsoft.com?

**Comment by AbelHu** [comment]
@cwackro It is an internal error when Azure internal components failover. After discussing with Azure feature team, CPI should handle this error but not throw this error.
I will create a PR for this.

**Comment by AbelHu** [comment]
It is fixed in the [commit](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/commit/ca8b1d8512ba8e1214ca0748c985c76234b2bd73)
