### ISSUE TITLE
Error when trying to upgrade from Bosh Azure CPIv7 to v8 or v9

### ISSUE THREAD

**Issue by cwackro** [cloudfoundry-incubator/bosh-azure-cpi-release#120]
Hello, when we try to upgrade to CPI v8 or v9 from v7 we get the following error in the run log
Even though we  replaced the "ssh_certificate" line with "ssh_pubic_key" in the bosh.yml file

********************
[Cmd Runner] 2016/04/04 14:49:09 DEBUG - Running command: ruby /tmp/erb-renderer775012399/erb-render.rb /tmp/erb-renderer775012399/erb-context.json /tmp/bosh-init-release659996273/extracted_jobs/cpi/templates/cpi.json.erb /tmp/rendered-jobs895232053/config/cpi.json
[Cmd Runner] 2016/04/04 14:49:09 DEBUG - Stdout:
[Cmd Runner] 2016/04/04 14:49:09 DEBUG - Stderr: /tmp/erb-renderer775012399/erb-render.rb:180:in `rescue in render': Error filling in template '/tmp/bosh-init-release659996273/extracted_jobs/cpi/templates/cpi.json.erb' for cpi/0 (line 43: #<RuntimeError: ssh_certificate has been replaced by ssh_public_key. Please read https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/README.md.>) (RuntimeError)
        from /tmp/erb-renderer775012399/erb-render.rb:166:in `render'
        from /tmp/erb-renderer775012399/erb-render.rb:191:in `<main>'
[Cmd Runner] 2016/04/04 14:49:09 DEBUG - Successful: false (1)
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/erb-renderer775012399
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/rendered-jobs895232053
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/stemcell-manager690346780
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/bosh-init-release260197594
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/bosh-init-release659996273
[Main] 2016/04/04 14:49:09 ERROR - Panic: runtime error: index out of range
********************
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/Godeps/_workspace/src/github.com/cloudfoundry/bosh-utils/logger/logger.go:134 (0x46c33e)
/usr/local/go/src/runtime/asm_amd64.s:403 (0x43bf85)
/usr/local/go/src/runtime/panic.go:387 (0x4139d8)
/usr/local/go/src/runtime/panic.go:12 (0x412b6e)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/installation/installer.go:78 (0x4d3820)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cpi/release/installer.go:37 (0x4c73ec)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/ui/stage.go:65 (0x47ba91)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cpi/release/installer.go:39 (0x4c6798)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cpi/release/installer.go:48 (0x4c6949)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deployment_preparer.go:176 (0x45625e)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deploy_cmd.go:74 (0x453529)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cmd/runner.go:27 (0x4621f7)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/main.go:42 (0x401352)
/usr/local/go/src/runtime/proc.go:63 (0x415523)
/usr/local/go/src/runtime/asm_amd64.s:2232 (0x43dfe1)

********************

We can provide full log to a secure location.

Thanks in advance :)

**Comment by AbelHu** [comment]
Did you remove ssh_certificate in the manifest?
You can send the log to me chou.hu@microsoft.com<mailto:chou.hu@microsoft.com>.

Best Regards,
Abel HU

? 2016?4?4??22:55?cwackro <notifications@github.com<mailto:notifications@github.com>> ???


Hello, when we try to upgrade to CPI v8 or v9 from v7 we get the following error in the run log
Even though we replaced the "ssh_certificate" line with "ssh_pubic_key" in the bosh.yml file

________________________________

[Cmd Runner] 2016/04/04 14:49:09 DEBUG - Running command: ruby /tmp/erb-renderer775012399/erb-render.rb /tmp/erb-renderer775012399/erb-context.json /tmp/bosh-init-release659996273/extracted_jobs/cpi/templates/cpi.json.erb /tmp/rendered-jobs895232053/config/cpi.json
[Cmd Runner] 2016/04/04 14:49:09 DEBUG - Stdout:
[Cmd Runner] 2016/04/04 14:49:09 DEBUG - Stderr: /tmp/erb-renderer775012399/erb-render.rb:180:in rescue in render': Error filling in template '/tmp/bosh-init-release659996273/extracted_jobs/cpi/templates/cpi.json.erb' for cpi/0 (line 43: #<RuntimeError: ssh_certificate has been replaced by ssh_public_key. Please read https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/README.md.>) (RuntimeError)
from /tmp/erb-renderer775012399/erb-render.rb:166:inrender'
from /tmp/erb-renderer775012399/erb-render.rb:191:in `

'
[Cmd Runner] 2016/04/04 14:49:09 DEBUG - Successful: false (1)
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/erb-renderer775012399
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/rendered-jobs895232053
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/stemcell-manager690346780
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/bosh-init-release260197594
[File System] 2016/04/04 14:49:09 DEBUG - Remove all /tmp/bosh-init-release659996273
[Main] 2016/04/04 14:49:09 ERROR - Panic: runtime error: index out of range

________________________________

/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/Godeps/_workspace/src/github.com/cloudfoundry/bosh-utils/logger/logger.go:134<http://github.com/cloudfoundry/bosh-init/Godeps/_workspace/src/github.com/cloudfoundry/bosh-utils/logger/logger.go:134> (0x46c33e)
/usr/local/go/src/runtime/asm_amd64.s:403 (0x43bf85)
/usr/local/go/src/runtime/panic.go:387 (0x4139d8)
/usr/local/go/src/runtime/panic.go:12 (0x412b6e)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/installation/installer.go:78<http://github.com/cloudfoundry/bosh-init/installation/installer.go:78> (0x4d3820)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cpi/release/installer.go:37<http://github.com/cloudfoundry/bosh-init/cpi/release/installer.go:37> (0x4c73ec)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/ui/stage.go:65<http://github.com/cloudfoundry/bosh-init/ui/stage.go:65> (0x47ba91)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cpi/release/installer.go:39<http://github.com/cloudfoundry/bosh-init/cpi/release/installer.go:39> (0x4c6798)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cpi/release/installer.go:48<http://github.com/cloudfoundry/bosh-init/cpi/release/installer.go:48> (0x4c6949)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deployment_preparer.go:176<http://github.com/cloudfoundry/bosh-init/cmd/deployment_preparer.go:176> (0x45625e)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cmd/deploy_cmd.go:74<http://github.com/cloudfoundry/bosh-init/cmd/deploy_cmd.go:74> (0x453529)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/cmd/runner.go:27<http://github.com/cloudfoundry/bosh-init/cmd/runner.go:27> (0x4621f7)
/tmp/build/src/gopath/src/github.com/cloudfoundry/bosh-init/main.go:42<http://github.com/cloudfoundry/bosh-init/main.go:42> (0x401352)
/usr/local/go/src/runtime/proc.go:63 (0x415523)
/usr/local/go/src/runtime/asm_amd64.s:2232 (0x43dfe1)

________________________________

We can provide full log to a secure location.

Thanks in advance :)

-

**Comment by AbelHu** [comment]
@cwackro You have a typo in your BOSH manifest. ssh_pubic_key should be ssh_public_key.

**Comment by AbelHu** [comment]
I guess it is resolved. @cwackro can reactive it if not.

**Comment by cwackro** [comment]
Thanks alot for your help.
Yep, Typo was the reason for the failure
