### ISSUE TITLE
Application deployed not accessible from browser

### ISSUE THREAD

**Issue by madhurig** [cloudfoundry-incubator/bosh-azure-cpi-release#129]
Following the instructions from https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/guidance.md,  the bosh and cloud foundry deployment completed successfully. I was also able to push the sample application to the cloud foundry instance but unable to reach deployed application from the browser. cf app shows the app as running successfully. 
What could cause this issue? Seems to be something to do with routes of the public IP.

**Comment by AbelHu** [comment]
Which domain name are you using in your cf manifest? If you are using Azure template to deploy your environment, you should access your application in your browser by this URL https://YOUR-APP-NAME.CF-PUBLIC-IP.xip.io

**Comment by madhurig** [comment]
@AbelHu : Thank you, I used the azure template, so I have to use the IP, I didn't register a domain name. The documentation says http://game-2048.REPLACE_WITH_CLOUD_FOUNDRY_PUBLIC_IP.xip.io/  should work but it doesn't. The https:// link shows the cert warning but comes up.

**Comment by AbelHu** [comment]
Have you pushed the app game-2048?
You can type 'cf apps' to check the status of your app and find the URL to access.
You should ignore the cert warning and continue to access it in the browser.

Best Regards,
Abel HU
Sent from my iPhone

? 2016?4?22??21:44?Madhuri Gummalla <notifications@github.com<mailto:notifications@github.com>> ???


@AbelHu<https://github.com/AbelHu> : Thank you, I used the azure template, so I have to use the IP, I didn't register a domain name. The documentation says http://game-2048.REPLACE_WITH_CLOUD_FOUNDRY_PUBLIC_IP.xip.io/<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fgame-2048.REPLACE_WITH_CLOUD_FOUNDRY_PUBLIC_IP.xip.io%2f&data=01%7c01%7cChou.Hu%40microsoft.com%7c984156c7b85544ddb9b708d36ab43029%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=XAYFxZRTNdl67xfkBvdycRdu%2blarPee%2bop2Yq6KhcLM%3d> should work but it doesn't. The https:// link shows the cert warning but comes up.

-

**Comment by madhurig** [comment]
Yes app is deployed and cf apps shows the status as running. You can see it at https://game-2048.191.237.41.150.xip.io/

**Comment by AbelHu** [comment]
@madhurig After CF is deployed, you can use any other machine to deploy your apps.

**Comment by madhurig** [comment]
@AbelHu thank you, I am able to access the cf deployment.
