### ISSUE TITLE
Allow CPI to use Azure data disk as an ephemeral disk

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#130]
It appears that Azure when migrating VMs blows away temporary disks. Turns out that CPI currently [uses temporary disks](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/cloud.rb#L408) for VM's ephemeral storage. Since BOSH places software packages it installs on the ephemeral disk we do not want to lose disk contents on *reboots* (On AWS instance storage is kept around for reboots, but not for start/stop operations).

Proposed solution is to attach additional data disk (inside create_vm, before VM boots up) and use that for ephemeral storage instead of using temporary disk (temporary disk will still be attached, but unused). Then also delete this data disk (inside delete_vm) when VM is no longer needed. This is very similar to what we do for custom sized ephemeral disks on AWS.

Given frequency of reboots I think this should be the new default behaviour for the CPI. We can default to 10gb sized ephemeral disks and allow people to set custom size as part of resource pool configuration (next to instance_type key).

For example:

```
resource_pools:
- name: test
  cloud_properties:
    instance_type: Standard_D2
    ephemeral_disk: 
      size: 20_000
```

**Comment by cppforlife** [comment]
+1 from gary on cloudops. run into this several times.

**Comment by svrc-pivotal** [comment]
+1 for using data disks

**Comment by AbelHu** [comment]
Please see PR #134

**Comment by haydonryan** [comment]
Looks like this got reported in this issue too: https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/71

We are seeing this on a customer site.  +1 for
