### ISSUE TITLE
Blocked from contacting internal Azure components

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry-incubator/bosh-azure-cpi-release#136]
We were working on a network with ... *unusual* characteristics: the bosh director was blocked from contacting external IPs. This surfaced as we were attempting to upload a stemcell; it only timed out after 16 minutes, failing to connect to `management.azure.com`. 

A short-term workaround: have shorter timeouts when contacting internal Azure components.

**Comment by cppforlife** [comment]
I think it also would be nice to include full address (ip) and port to where it's trying to connect. It also may be worth to add most likely error reason like we did for AWS: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/commit/ec62d78c16c857f1a6538a9365b4c8f3204d0a57

**Comment by AbelHu** [comment]
@pronoiac Could you share the logs to me (chou.hu@microsoft.com) for better understanding?
1. Are you using `bosh upload stemcell xxxx` to upload stemcell?
2. What do you mean `the bosh director was blocked from contacting external IPs`? I guess you created a firewall rules to block all TCP connections from the BOSH director VM to external IPs, is it right?

**Comment by cppforlife** [comment]
@AbelHu 

1. yes
2. firewall rules didnt allow outgoing traffic
3. v10

**Comment by AbelHu** [comment]
About this issue,
1. The latest CPI has included full address (ip) and port in the logs. Please see code [here](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/cloud.rb#L388).
2. There is an [issue](https://github.com/Azure/azure-ruby-asm-core/issues/16) in azure-ruby-asm-core. We will wait the fix and then close this issue.

**Comment by AbelHu** [comment]
The [issue](https://github.com/Azure/azure-ruby-asm-core/issues/16) in azure-ruby-asm-core has been fixed. After the new azure-storage-ruby is released, CPI will upgrade sdk.
