### ISSUE TITLE
Have Azure PowerShell commands with Azure CLI commands

### ISSUE THREAD

**Issue by dwallraff** [cloudfoundry-incubator/bosh-azure-cpi-release#140]
In many corporate environments, proxies are in heavy use. The Azure CLI does not respect proxies. Is it possible to add the equivalent Azure PowerShell commands to the http://bosh.io/docs/azure-resources.html page?

**Comment by AbelHu** [comment]
@dwallraff I filed an issue https://github.com/Azure/azure-xplat-cli/issues/2882. We also will consider to add Azure PowerShell commands in our guidance.

**Comment by AbelHu** [comment]
@dwallraff Can you try below command before you run azure-cli commands.

export HTTP_PROXY="http://PROXY-HOST:PROXY-PORT"
or 
export HTTPS_PROXY="https://PROXY-HOST:PROXY-PORT"

**Comment by dwallraff** [comment]
This is on windows, so there's no export command. We added them as an env var and still no go. We're not looking to have this fixed in the azure cli (although that would be nice), but more looking for the equivalent powershell commands to run to setup storage accounts, service principals, NSGs, etc.

**Comment by AbelHu** [comment]
You can try 'set' instead of 'export' on Windows.

Best Regards,
Abel HU
Sent from my iPhone




On Wed, May 18, 2016 at 8:37 AM -0700, "Dave Wallraff" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is on windows, so there's no export command. We added them as an env var and still no go. We're not looking to have this fixed in the azure cli (although that would be nice), but more looking for the equivalent powershell commands to run to setup storage accounts, service principals, NSGs, etc.

-

**Comment by cbittne** [comment]
Here is the output:
C:\Users\username>set HTTP_PROXY="http://squid.company.com:3128"

C:\Users\username>set HTTPS_PROXY="https://squid.company.com:3128"

C:\Users\username>azure login
info:    Executing command login
+ Authenticating...
error:   tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
info:    Error information has been recorded to H:\.azure\azure.err
error:   login command failed


C:\Users\username>

**Comment by AbelHu** [comment]
@dwallraff You can use below command to set proxy in command line before using azure cli.

```
set HTTPS_PROXY=http://ROXY-HOST:PROXY-PORT
```

**Comment by cbittne** [comment]
Unfortunately, we have tried this in multiple iterations and that does not work for us.


USAL0134:~ cbittne$ set https_proxy=https://squid.icrp.mrll.com:3128

USAL0134:~ cbittne$ azure login -u cbittne-a@mymerrillcorp.onmicrosoft.com<mailto:cbittne-a@mymerrillcorp.onmicrosoft.com>

info:    Executing command login

Password: **************

+ Authenticating...

error:   connect ENETUNREACH 104.210.208.20:443

error:   Error information has been recorded to /Users/cbittne/.azure/azure.err

error:   login command failed


USAL0134:~ cbittne$ set HTTPS_PROXY=https://squid.icrp.mrll.com:3128

USAL0134:~ cbittne$ azure login -u cbittne-a@mymerrillcorp.onmicrosoft.com<mailto:cbittne-a@mymerrillcorp.onmicrosoft.com>

info:    Executing command login

Password: **************

+ Authenticating...

error:   connect ENETUNREACH 104.210.208.20:443

error:   Error information has been recorded to /Users/cbittne/.azure/azure.err

error:   login command failed



--
Chad Bittner
Merrill Corporation
O: 651.632.4060
C: 612.817.0494
chad.bittner@merrillcorp.com<mailto:chad.bittner@merrillcorp.com>
[emailsig.jpg]

**Comment by AbelHu** [comment]
@cbittne Did you try the command in the command line on `Windows`? I tried to use an invalid proxy in my desktop(Win2012R2) and got below error. But if I use a valid proxy, it works. I use azure-cli `0.10.1` and `ccproxy` as my proxy service.
Could you provide your cli verion by running 'azure -v' and your Windows version?

![image](https://cloud.githubusercontent.com/assets/6416187/18340234/6db94c9e-75d6-11e6-8ef9-99623ca3dfcb.png)

**Comment by cbittne** [comment]
I am using Mac OS X and we have squid proxy servers for un-authenticate access and mcafee webproxy for authenticated access.  I have verified the proxy information both and tried both.  I currently have azure cli version 0.10.2 installed.



--
Chad Bittner
Merrill Corporation
O: 651.632.4060
C: 612.817.0494
chad.bittner@merrillcorp.com<mailto:chad.bittner@merrillcorp.com>
[cid:image001.png@01D2099C.9A9E4EE0]

**Comment by AbelHu** [comment]
@cbittne We also tested in Mac OS X. Above command also works.

![image](https://cloud.githubusercontent.com/assets/6416187/18692326/47bdec3a-7f4e-11e6-8b0f-035fe0c9f83d.png)
