### ISSUE TITLE
generate.exe ended with "panic: Expected document start at line 0, column 0"

### ISSUE THREAD

**Issue by ritazh** [cloudfoundry-incubator/bosh-azure-cpi-release#146]
Following the guide [here](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/push-your-first-net-application-to-cloud-foundry-on-azure) to push .net app and this [guide](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/deploy-diego) to deploy diego. 

After running `all-in-one\generate.exe` with local variables, getting this error:

```
panic: Expected document start at line 0, column 0

goroutine 1 [running]:
main.FailOnError(0x25db40, 0xc082003ce0)
        C:/diego-windows-release/greenhouse-install-script-generator/src/generat
e/generate.go:306 +0x57
main.main()
        C:/diego-windows-release/greenhouse-install-script-generator/src/generat
e/generate.go:118 +0xbe5

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0xc08208c0b0)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc08208c0b0)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3
```

**Comment by AbelHu** [comment]
Please check the versions in your environment and make sure that the versions match below versions. If you use a different version, you may hit a compatibility issue because BOSH and generator are always changing.

garden-linux-release: 0.334.0
etcd-release: 36
diego-release: 0.1455.0
bosh:255.3

**Comment by ritazh** [comment]
Thanks @AbelHu Seems I have everything else with the same version except bosh, which is 256.2, as that is the latest from the ARM template as of now. Is there anything I can do to fix this or do I need to change the bosh version to 255.3? Thanks!

**Comment by AbelHu** [comment]
You can try to upgrade the generator to the latest version. If it does not work, it is better for you to change BOSH version to 255.3. Otherwise you need to debug the failure by yourself

**Comment by ritazh** [comment]
Thanks @AbelHu Is there any documentation for how to upgrade the generator?

**Comment by AbelHu** [comment]
I think you may be able to find the guide in GitHub repro for Diego Windows.

Best Regards,
Abel HU
Sent from my iPhone




On Fri, May 20, 2016 at 9:05 AM -0700, "Rita Zhang" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @AbelHu<https://github.com/AbelHu> Is there any documentation for how to upgrade the generator?

-

**Comment by ritazh** [comment]
Seems this generator only works with Bosh 255.3. Closing the issue.
