### ISSUE TITLE
improve cpi behavior of picking default ephemeral disk size based on instance type

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#148]
instead of picking just preconfigured size, let's make the cpi a bit more magical and have a table of instance types with their ephemeral disk sizes. we've actually added something similar to aws cpi: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/f23cc8f20ea74e68855089b3fca65247d468d8c2/src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb#L165

if instance type is not found in the list (let's say when new one is introduced), let's just fallback to some default size (whatever it is today).

i would also recommend just hard coding the list and updating it over time instead of making an extra call to azure apis (if available) to keep this as fast as possible and not cut into api rate limits.

**Comment by AbelHu** [comment]
Fix it in this commit https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/commit/e961182d71f231b2b7b020027d49a898d9b34794
