### ISSUE TITLE
Azure CPI fails to get auth token when attempting to create stemcell

### ISSUE THREAD

**Issue by johnsirmon** [cloudfoundry-incubator/bosh-azure-cpi-release#149]
STDERR: 'I, [2016-06-01T20:54:35.553991 #32599]  INFO -- : http_get - trying to get https://management.azure.com//subscriptions/[REDACTED]/resourceGroups/ci-iaas-resources/providers/Microsoft.Storage/storageAccounts/iaasenablementcistore?api-version=2015-05-01-preview
I, [2016-06-01T20:54:35.554234 #32599]  INFO -- : get_token - trying to get/refresh Azure authentication token
D, [2016-06-01T20:54:35.554457 #32599] DEBUG -- : get_token - authentication_endpoint: https://login.microsoftonline.com/[REDACTED]/oauth2/token?api-version=2015-05-01-preview
D, [2016-06-01T20:54:35.554729 #32599] DEBUG -- : get_token - request.header:
D, [2016-06-01T20:54:35.554811 #32599] DEBUG -- :       accept-encoding = gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2016-06-01T20:54:35.554881 #32599] DEBUG -- :       accept = */*
D, [2016-06-01T20:54:35.554951 #32599] DEBUG -- :       user-agent = Ruby
D, [2016-06-01T20:54:35.555016 #32599] DEBUG -- :       content-type = application/x-www-form-urlencoded
D, [2016-06-01T20:54:35.555084 #32599] DEBUG -- : get_token - request.body:
grant_type=client_credentials&client_id=[REDACTED]&client_secret=[REDACTED]&resource=https%3A%2F%2Fmanagement.azure.com%2F&scope=user_impersonation
E, [2016-06-01T20:54:36.531624 #32599] ERROR -- : http_get_response - #<Bosh::AzureCloud::AzureError: get_token - http code: 400>
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:910:in `get_token'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:944:in `http_get_response'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1068:in `http_get'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:82:in `get_resource_by_id'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:830:in `get_storage_account'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:825:in `get_storage_account_by_name'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:13:in `initialize'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:384:in `new'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:384:in `init_azure'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:19:in `initialize'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/bin/azure_cpi:27:in `new'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/bin/azure_cpi:27:in `block in <main>'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3215.3.1/lib/bosh/cpi/cli.rb:69:in `call'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3215.3.1/lib/bosh/cpi/cli.rb:69:in `run'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'
'
[cpiCmdRunner] 2016/06/01 20:54:36 DEBUG - Rescued Bosh::Clouds::CloudError: http_get_response - #<Bosh::AzureCloud::AzureError: get_token - http code: 400>
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:910:in `get_token'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:944:in `http_get_response'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1068:in `http_get'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:82:in `get_resource_by_id'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:830:in `get_storage_account'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:825:in `get_storage_account_by_name'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:13:in `initialize'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:384:in `new'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:384:in `init_azure'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:19:in `initialize'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/bin/azure_cpi:27:in `new'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/bin/azure_cpi:27:in `block in <main>'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3215.3.1/lib/bosh/cpi/cli.rb:69:in `call'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3215.3.1/lib/bosh/cpi/cli.rb:69:in `run'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'. backtrace: /root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/helpers.rb:56:in `cloud_error'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1001:in `rescue in http_get_response'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:941:in `http_get_response'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1068:in `http_get'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:82:in `get_resource_by_id'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:830:in `get_storage_account'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:825:in `get_storage_account_by_name'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:13:in `initialize'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:384:in `new'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:384:in `init_azure'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:19:in `initialize'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/bin/azure_cpi:27:in `new'
/root/.bosh_init/installations/4d167b48-d56a-40f0-5bf3-b37412df6962/packages/bosh_azure_cpi/bin/azure_cpi:27:in `block in <main>'
/root/.bosh_init/installations/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3215.3.1/lib/bosh/cpi/cli.rb:69:in `call'
/root/.bosh_init/installations/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3215.3.1/lib/bosh/cpi/cli.rb:69:in `run'
/root/.bosh_init/installations//packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'

**Comment by thomas1206** [comment]
@johnsirmon , what's the result when you run the following command?
azure login --username $CLIENT_ID --password $CLIENT_SECRET --service-principal --tenant $TENANT_ID --environment $ENVIRONMENT

From the error log, seems your sp is not valid.

**Comment by AbelHu** [comment]
Confirm to be a typo issue.
