### ISSUE TITLE
supportability get_token need more granularity in error messages

### ISSUE THREAD

**Issue by johnsirmon** [cloudfoundry-incubator/bosh-azure-cpi-release#150]
specifically...        

response = http(uri).request(request)
        if response.code.to_i == HTTP_CODE_OK
          @token = JSON(response.body)
          @logger.debug("get_token - token is\n#{@token}")
        elsif response.code.to_i == HTTP_CODE_UNAUTHORIZED
          raise AzureError, "get_token - Azure authentication failed: invalid tenant id, client id or client secret."
        else
          raise AzureError, "get_token - http code: #{response.code}" <---------------not helpful

**Comment by AbelHu** [comment]
@johnsirmon Azure should return 401 HTTP_CODE_UNAUTHORIZED when the spn is invalid. But in your case, there is a typo in the client_secret and Azure returns 400 HTTP_CODE_BADREQUEST.
We will catch 400 error and log the reason in the log.

**Comment by AbelHu** [comment]
@johnsirmon Close it since it has been fixed in v13 in this [commit](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/commit/1bf6a88e47af21f1daf6c454833f17586215894d)
