### ISSUE TITLE
bosh release 404 not found.

### ISSUE THREAD

**Issue by samueldeng** [cloudfoundry-incubator/bosh-azure-cpi-release#157]
The url in following command has been removed.
```
bosh upload release https://cf-contrib.s3.amazonaws.com/boshrelease-cf-services-contrib-6.tgz
```
There is a the [official url](https://bosh.io/releases/github.com/cloudfoundry-community/cf-services-contrib-release?all=1) instead.
```
bosh upload release https://bosh.io/d/github.com/cloudfoundry-community/cf-services-contrib-release
```

**Comment by AbelHu** [comment]
Thanks for the report, @samueldeng. 
@bingosummer Please update [README](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/e7b9440a19e0b714e91569b00b911051a5cb7b0c/docs/advanced/deploy-mongodb/README.md)
