### ISSUE TITLE
Slow DNS Query 

### ISSUE THREAD

**Issue by samueldeng** [cloudfoundry-incubator/bosh-azure-cpi-release#159]
In config file: [deploy-mysql/sample_azure_stub.yml] (https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/deploy-mysql/sample_azure_stub.yml)

using dns ``168.63.129.16`` is too slow in mooncake.
It is better to use ``8.8.8.8``, ``114.114.114.114`` instead.

I have test 8.8.8.8 and 168.63.129.16 100 times.
``8.8.8.8`` is faster than ``168.63.129.16 83`` times.

**Comment by bingosummer** [comment]
@samueldeng 
Thanks for your suggestion.

There is a possibility that `8.8.8.8` is blocked in AzureChinaCloud(Mooncake) due to the well-known network issue in China. Did you hit the blocking issue in your test?

We are considering using another DNS instead of `168.63.129.16` for AzureChinaCloud.

**Comment by bingosummer** [comment]
We've added a secondary DNS. For `AzureChinaCloud`, the CNNINC DNS server `1.2.4.8` is used. I think, we can close this issue.

**Comment by cppforlife** [comment]
Non Azure related issues with DNS at this point.
