### ISSUE TITLE
allow use to associate application gateways in vm cloud properties

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#169]
let's add `application_gateways: ["gw1", "gw2"]` to http://bosh.io/docs/azure-cpi.html#resource-pools so that VMs are associated with application gateways.

cc @dsboulder

**Comment by geofffranks** [comment]
This would be useful for us currently. I had assumed support was in place, since there're docs on using Web Application Gateways with CF, though on closer inspection they were all using manual IP associations

**Comment by AbelHu** [comment]
@cppforlife Thanks for the suggestion. That is in our plan and the code is almost ready. We are still waiting some missing features of Application Gateway and will submit the PR after all testing is finished.
cc @geofffranks
