### ISSUE TITLE
allow bosh to be used with a1 instance size and persistent disk that can be migrated

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#170]
currently cpi adds an additional ephemeral disk as a data disk. a1 instance size only allows 2 data disks which means that bosh cannot migrate persistent disks (attaches 2 disks at one time to a single vm). to support this scenario let's add `root_disk.size` configuration to https://bosh.io/docs/azure-cpi.html#resource-pools just like `ephemeral_disk.size`. this would also require stemcell update similarly to how google stemcell does it [1]. let's not set ephemeral disk for the agent when ephemeral_disk is nil. for now let's continue to default ephemeral_disk but eventually we'll just switch to root_disk configuration.

[1] https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/stages/bosh_google_agent_settings/apply.sh#L10

**Comment by cppforlife** [comment]
cc @dsboulder

**Comment by dsboulder** [comment]
Also applies to all instance classes that allow just 1 or 2 data disks, such as:
* Standard_A0
* Standard_A1
* Standard_DS1_v2
* Standard_F1s

**Comment by AbelHu** [comment]
Code is merged.

**Comment by dsboulder** [comment]
In order to verify this, I think I need a new stemcell right?  @cppforlife can I get one?

**Comment by AbelHu** [comment]
@dsboulder Maybe you can verify it with our private stemcell build as below before the official build.
```
url: https://cloudfoundry.blob.core.windows.net/share/stemcell-for-resize.tgz
sha1: 484fa57cd787daddb266a4dbe43198a4f217d42c
```

**Comment by dsboulder** [comment]
I tried it, got it to work with a cloud_config like this:

```
  cloud_properties:
    instance_type: Standard_F1
    root_disk:
      size: 19384
    ephemeral_disk:
      use_root_disk: true
    storage_account_name: dsomaug9storageaccount
```

Can we add all these new options to the docs?  It was hard to figure them out.

**Comment by AbelHu** [comment]
@dsboulder Sorry for that I forgot to tell you how to configure it. Actually we have created a PR [#181](https://github.com/cloudfoundry/docs-bosh/pull/181/files) for docs-bosh.
