### ISSUE TITLE
cpi should automatically set availability_set based on bosh.instance_group_id

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#171]
bosh director will automatically pass in `bosh.instance_group_name` into vm cloud properties in create_vm CPI call. if that value is present (to be backwards compatible and work with bosh-init which will not pass this in) use that as availability set name unless `availability_set` is specified. this will improve experience with using multiple availability sets. use platform_update_domain_count/platform_fault_domain_count for those configurations.

**Comment by cppforlife** [comment]
cc @dsboulder

**Comment by cppforlife** [comment]
It will be inside env hash (not vm cloud properties) as `bosh.group_name`.

**Comment by dsboulder** [comment]
I verified this.  Thank you!

**Comment by dsboulder** [comment]
@cppforlife why did you suggest the bosh.group_name thing under env hash?

**Comment by cppforlife** [comment]
director will set this value automatically in the next release.
