### ISSUE TITLE
cpi should automatically pick storage account for new vms

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#172]
given that it's hard for a user to pick a storage account for each vm, we want to cpi to be a little smarter about how it use default storage account. instead of using single storage account for the cpi let's add an option to specify a pattern (ie my-storage-account-*) that will effectively resolve into my-storage-account-0...my-storage-account-100. when vm/disk is created if storage account is not explicitly specified in its cloud properties, cpi will query api for current usage in each storage account (how many disks are in that storage account), ignore storage accounts that have >30 disks, and randomly pick storage account for use.

cc @dsboulder

**Comment by dsboulder** [comment]
I verified this, thank you!
