### ISSUE TITLE
CPI should ignore conflict error when another process has started the deletion

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry-incubator/bosh-azure-cpi-release#173]
We're getting errors during delete deployments of cf.

```
Unknown CPI error 'Bosh::AzureCloud::AzureConflictError' with message 'http_delete - http code: 409 message: {
  "error": {
    "code": "Conflict",
    "message": "The request failed due to conflict with a concurrent request. "
  }
}' 
```

Logs sent via email.

**Comment by cppforlife** [comment]
@haydonryan do we know what else was deleting?

**Comment by haydonryan** [comment]
sorry no.

On Tue, Jul 19, 2016 at 1:29 PM Dmitriy Kalinin

<
mailto:Dmitriy Kalinin <notifications@github.com>
> wrote:

https://github.com/haydonryan
do we know what else was deleting?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/173#issuecomment-233706478
, or

**Comment by AbelHu** [comment]
@haydonryan Thanks for the report. We will fix this issue. @cppforlife , at the same time, multiple process were trying to delete the availability set. That is why Azure returns 'Conflict'.

**Comment by cppforlife** [comment]
im not sure it makes sense to delete availability sets at all given that there might be paralle delete_vm and create_vm calls, so there is always going to be a race.

**Comment by AbelHu** [comment]
@cppforlife Yes. Maybe we should not delete availability sets.

**Comment by AbelHu** [comment]
The code is merged so close this.
