### ISSUE TITLE
Avoid using storage account tables to keep track of copying process

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#178]
Currently we use storage table to keep track of copying operation. In theory there is still a race between query and insert, but probably doesnt happen often. Is it possible to query Azure API to see if any copies are in progress? Alternatively we can use local file system to "lock" copying operation.

Goal is to not have tables to simplify setup and allow default storage account to be on premium storage.

**Comment by AbelHu** [comment]
The race between query and insert is handled in [CPI code](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb#L110-L114)

Later we can consider to remove the table dependency.
