### ISSUE TITLE
CPI job name inconsistent with other CPI releases

### ISSUE THREAD

**Issue by maryamklabib** [cloudfoundry-incubator/bosh-azure-cpi-release#180]
We noticed an inconsistency in the azure CPI that we wanted to point out. 
The CPIs for vSphere, vCloud, AWS and OpenStack follow the convention that the CPI job contains the name of the infrastructure (e.g. `vsphere_cpi`). 

![screen shot 2016-07-22 at 3 31 46 pm](https://cloud.githubusercontent.com/assets/4147717/17073054/20636f8a-5022-11e6-8871-3d33f84acbd5.png)

The Azure CPI release just calls it `cpi`. 

![screen shot 2016-07-22 at 3 31 31 pm](https://cloud.githubusercontent.com/assets/4147717/17073051/1b3ffb40-5022-11e6-853c-62e3d5c1a29c.png)

Would it be possible to change it to follow this convention?

cc @cppforlife @matt-royal

**Comment by AbelHu** [comment]
@cppforlife How do you think? Change [cpi](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/jobs/cpi) to azure_cpi?

**Comment by cppforlife** [comment]
@AbelHu yup. this makes sense. let's do for the upcoming release version.
