### ISSUE TITLE
CPI packaging should not fail on OS X with Homebrew-installed OpenSSL

### ISSUE THREAD

**Issue by coreyti** [cloudfoundry-incubator/bosh-azure-cpi-release#184]
There was some discussion about this in the Slack channel at the beginning of June, in which we determined that the `LDFLAGS` for the Ruby installation should include the path to OpenSSL, as installed by Homebrew. 

The fix: Add `/usr/local/opt/openssl` to the `--with-opt-dir` option. The full `LDFLAGS` setting should be:

```bash
LDFLAGS="-Wl,-rpath -Wl,${BOSH_INSTALL_TARGET}" CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=/usr/local/opt/openssl:${BOSH_INSTALL_TARGET} --without-gmp
```

**Comment by AbelHu** [comment]
@coreyti Thanks for the reporting. We will fix it.
