### ISSUE TITLE
Deployment failures using ARM template with passwords containing special characters

### ISSUE THREAD

**Issue by CraigWiand** [cloudfoundry-incubator/bosh-azure-cpi-release#192]
Filing issue here per [these](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/via-arm-templates/deploy-bosh-via-arm-templates.md) instructions

Currently the template to deploy Bosh does not do parameter validation (e.g. via regex) and the Bash command that the [template generates]( https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/azuredeploy.json#L546) leaves the password un-quoted due to the fact that double quotes are used for both the inner and outer commands.  If [special characters ](http://www.tldp.org/LDP/abs/html/special-chars.html)in Bash or Python are passed as parameters it can have unexpected results. For example, a hash sign being used in a password results in a command like this through the custom script extension deployment:

_bash -l -c "./setup_env 4ea920e3-5e63-4637-ae30-bc3119135981 1b842d63-d896-44fb-b7e4-d7e9cf021534 "#MyPassword" >/home/user/install.log 2>&1"_

the result is that the password parameter is never passed to the install script and, to complicate the matter, the install.log file is never created.  Failures can also be experienced using other Bash reserved characters (e.g. $) 

I believe this could potentially be addressed by generating a string which either alternating single and double-quotes or escaping the double-quotes passed to the bash command, similar to:

**Alternating single and double-quotes**
`"commandToExecute": "[concat('bash -l -c \"./setup_env', ' ', parameters('tenantID'), ' ', parameters('clientID'), ' \'', parameters('clientSecret'), '\' >/home/', parameters('adminUsername'), '/install.log 2>&1\"')]"`
      
or **escaping the double-quotes**  
`"commandToExecute": "[concat('bash -l -c \"./setup_env', ' ', parameters('tenantID'), ' ', parameters('clientID'), ' \\\"', parameters('clientSecret'), '\\\" >/home/', parameters('adminUsername'), '/install.log 2>&1\"')]"`

**Comment by bingosummer** [comment]
Thanks @CraigWiand for raising this issue. We are fixing this issue. The codes are reviewing internally. The idea is to base64-encode `client_secret`. What do you think?

**Comment by CraigWiand** [comment]
Thanks for looking into this.  It seems there are two points:
1. handling the special character issue.  If I understand your link, this should be addressed by using single quotes with [https://github.com/bingosummer/azure-quickstart-templates/commit/1c4084f42d31d1512e3e5f843590213a59a66995] fix.
2. is how to better convey the password such that is not easily readable; and that is to base-64 encode.

is that correct?  or are you looking to encode to avoid special characters instead of 1 solution of single quote described above?

**Comment by bingosummer** [comment]
1. base64-encoding client_secret can fix the issue of special character as a Bash or Python command parameter. When we put the client_secret into bosh.yml, the script `setup_env.py` will decode the value.
2. If we don't have the single quotes in bosh.yml, the client_secret which starts with `#` will be regarded as a comment.

With the above changes, the `client_secret` can be passed correctly.

**Comment by bingosummer** [comment]
https://github.com/Azure/azure-quickstart-templates/pull/2358 is merged.
