### ISSUE TITLE
sudo permission of vcap on bosh director

### ISSUE THREAD

**Issue by Lickkylee** [cloudfoundry-incubator/bosh-azure-cpi-release#199]
I tried to deploy CF via bosh but always got error Timed out pinging to a865c689-0cb7-4211-9163-3276a3eb6e7a after 600 seconds. 
I logged in bosh director to retrieve logs for further analysis by user vcap but /var/vcap/bosh/log/ is owned by root. when trying to sudo to root, I was asked for password of vcap. I used ssh private keys to log in bosh director VM so I absolutely didn't know the password of user vcap. 
Is this by design? How can I get the logs for troubleshooting?

**Comment by bingosummer** [comment]
The default password is `c1oudc0w`.

Did you use the bosh-setup template to deploy BOSH and CF?
https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/via-arm-templates/deploy-bosh-via-arm-templates.md

**Comment by Lickkylee** [comment]
I used template, as well as manual way to deploy. 
Yes, you are right, the one from templates has the default password, but the one manual deployed seemed don't have default password. But the bosh.yml didn't have an entry to let me define the password of vcap.

**Comment by bingosummer** [comment]
I think, the password can't be specified in `bosh.yml`.
It seems that it's set when building the stemcell.
https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/etc/settings.bash

@cppforlife @AbelHu Please correct me if my understanding is wrong.

**Comment by cppforlife** [comment]
Here is an example of how you can set it: https://github.com/cloudfoundry/docs-bosh/blob/master/init-vsphere.html.md.erb#L41.

**Comment by bingosummer** [comment]
Thanks @cppforlife .

It seems that the password is generated by `mkpasswd  -m sha-512 -S 4gDD3aV0rdqlrKC -s <<< c1oudc0w`.

**Comment by AbelHu** [comment]
@bingosummer It seems like that the password of vcap is set to `c1oudc0w` by default in the latest stemcells.
@Lickkylee You can follow @bingosummer 's suggestion to create a encrypted password and set it in your manifest if you want to use a different password for vcap.

**Comment by akskap** [comment]
@cppforlife 

I just created a bosh-lite environment on Openstack environment using 

```
bosh create-env ~/Documents/workspace/bosh-deployment/bosh.yml \
  -o ~/Documents/workspace/bosh-deployment/openstack/cpi.yml \
  -o ~/Documents/workspace/bosh-deployment/bosh-lite.yml \
  -o ~/Documents/workspace/bosh-deployment/bosh-lite-runc.yml \
  -o ~/Documents/workspace/bosh-deployment/external-ip-with-registry-not-recommended.yml \

```

Any action with sudo for vcap user asks for a password. Can you please help with the default password that would have been used here ? I tried all suggestions above but din't work

**Comment by bingosummer** [comment]
@akskap 
You can follow https://bosh.io/docs/jumpbox. The ops file is https://github.com/cloudfoundry/bosh-deployment/blob/master/jumpbox-user.yml.
It will add a `jumpbox` user, which doesn't ask for a password for `sudo`.

**Comment by akskap** [comment]
@bingosummer Thanks a lot for the pointers. For targeting the cf environment from outside (using `cf api`), I am unable to reach the CF router VM in the CF deployment on bosh-lite. Is there anything I am missing ?

**Comment by bingosummer** [comment]
@akskap 
If you are using `bosh -e boshlite -d cf deploy ./cf-deployment.yml -o ./operations/bosh-lite.yml --vars-store cf-deployment-vars.yml -v system_domain="bosh-lite.com"`, then you should use `cf api https://api.bosh-lite.com --skip-ssl-validation` to target the CF api endpoint.
