### ISSUE TITLE
single-vm-cf.yml does not have api_z1

### ISSUE THREAD

**Issue by nishantsinha-5** [cloudfoundry-incubator/bosh-azure-cpi-release#216]
While deploying single vm cloud foundry as per the given guideline, single-vm-cf.yml does not contains the following section:
jobs:
- name: api_z1
  properties:
    nfs_server:
      allow_from_entries: [10.0.16.0/20]

Just to try we added the  10.0.48.0/20 CIDR in all entries of  "nfs_server" present in single-vm-cf.yml but it the deployment did not complete even after 24 hours, so we had to abort the same.

Kindly suggest where we should put the CIDR address in single-vm-cf.yml.

Thanks

**Comment by gossion** [comment]
Hi Nishant,
In single-vm-cf.yml, job cf_z1 contains most of jobs including api_z1. 
you can add your entries to [cf_z1 properties](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/single-vm-cf.yml#L148) `AND` [global properties](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/single-vm-cf.yml#L625), like this: 
```
    nfs_server:
      address: 10.0.16.4
      allow_from_entries: [10.0.16.0/20, 10.0.48.0/20]
```
Let me know the result.

**Comment by nishantsinha-5** [comment]
Hi gossion,

Thanks for the suggestion, we have followed the steps but while deploying with the updated yml we came across with the following error:

$ bosh -n deploy
Acting as user 'admin' on deployment 'single-vm-cf-on-azure' on 'bosh'
Getting deployment properties from director...
Detecting deployment changes
----------------------------
Releases
cf
  version type changed: String -> Fixnum
    - 238
    + 238

Compilation
No changes

Update
No changes

Resource pools
resource_postgres_z1
  stemcell
    version type changed: String -> Float
      - 3262.7
      + 3262.7
resource_z1
  stemcell
    version type changed: String -> Float
      - 3262.7
      + 3262.7

Disk pools
No changes

Networks
No changes

Jobs
cf_z1
  properties
    nfs_server
      ± allow_from_entries:
        + 10.0.48.0/20

Properties
nfs_server
  ± allow_from_entries:
    + 10.0.48.0/20

Deploying
---------
Director task 18
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
  Started preparing deployment > Preparing deployment. Done (00:00:01)
  Started preparing package compilation > Finding packages to compile. Done (00:00:00)
  Started updating job cf_z1 > cf_z1/0 (dcd2750e-17ed-4407-8762-b8b6c70be6ac) (canary). Failed: Action Failed get_task: Task                                 3f73e1dd-1f9e-42d6-7e15-5071f534ae70 result: 1 of 4 post-start scripts failed. Failed Jobs: rep. Successful Jobs: bbs, uaa, c                                loud_controller_ng. (00:09:38)

Error 450001: Action Failed get_task: Task 3f73e1dd-1f9e-42d6-7e15-5071f534ae70 result: 1 of 4 post-start scripts failed. Fai                                led Jobs: rep. Successful Jobs: bbs, uaa, cloud_controller_ng.

Task 18 error
For a more detailed error report, run: bosh task 18 --debug

Kindly suggest on this.

Thanks

**Comment by gossion** [comment]
That is quite weird. 
Two questions: 
1. Did you change anything else in single-vm-cf.yml? As I know, the VM size(instance_type) of cf_z1 must be at least Standard_D2, if the VM size is smaller than Standard_D2, rep will fail to spin up.
2.  why you need to allow 10.0.48.0/20 to connect to this nfs_server? do you have other cf jobs(e.g. cell_z1) running on 10.0.48.0/20?

Thanks,
Guoxun

**Comment by nishantsinha-5** [comment]
To give you the background, I have successfully installed cloudfoundry using provided single-vm-cf.yml. Now I am trying to add windows stack to cloudfoundry and bosh-azure-cpi-release steps mentioned that we need to add 10.0.48.0/20 cidr in the yml and redeploy, this is where we are facing issue and above error trace is for the second deployment attempt.

**Comment by gossion** [comment]
Change properties.nfs_server.allow_from_entries would not break the deployment, I did the same change in my environment to single-vm-cf.yml and got it deployed successfully. 
Can you please try increasing VM size? We got the same issue ([link](https://github.com/cloudfoundry/diego-release/issues/176)), and solved the issue by increasing VM size.

**Comment by AbelHu** [comment]
Close this since it is not active.
