### ISSUE TITLE
Stripe storage account placement across each VM in an availability set

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry-incubator/bosh-azure-cpi-release#225]
Suggested enhancement.

Azure best practices here: 
https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-manage-availability?toc=%2fazure%2fvirtual-machines%2flinux%2ftoc.json

States at the bottom: _**"Use separate storage account for each VM in an Availability Set. Multiple VMs in the same availability set must NOT share the same storage account."**_

Unfortunately this seems to the opposite of the default behavior of the CPI, which assigns an availability set per resource pool/VM type, and then each VM per set to a single storage account.  

The \***storageaccountpattern**\* feature is a helpful interim solution to this, but uses a random array shuffle to place each VM across a set of storage accounts, rather than being predictably round-robin striped relative to storage account capacity.  One suggestion is to keep track of disks -> availability sets -> storage accounts somewhere to handle a round robin.   

This all seems fairly annoying and I'm not sure how much it's worth in terms of availability (are there any guarantees that different storage accounts are on different blob stamps behind the scenes?), but the language in the above article seems stronger than I remember from past advice on this topic.

**Comment by dsboulder** [comment]
+1 to this issue.  We just saw a customer trying to manage availability with the storage account pattern and failing to do so.
