### ISSUE TITLE
Can we support managed disks?

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry-incubator/bosh-azure-cpi-release#228]
There's a private preview of managed disks that partners and customers can try out.  Can we add support to the CPI for managed disks yet?  If so, that will let us gather feedback on how MD works with BOSH deployments.
@cppforlife

**Comment by geofffranks** [comment]
Any eta on when this might be available in the cpi?

**Comment by AbelHu** [comment]
@geofffranks We will release it this week. Now we hit one random issue with the latest CentOS stemcell v3363.9. It seems like to be an issue of the stemcell because we never hit this in v3312.7. We still need some time to investigate it.

**Comment by geofffranks** [comment]
Thanks!

**Comment by cppforlife** [comment]
yay for managed disks. nice work!
