### ISSUE TITLE
`Connection reset by peer - SSL_connect` error retry

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#234]
CPI or SDK should retry on "Connection reset by peer - SSL_connect" error (OpenSSL::SSL::SSLError, OpenSSL::X509::StoreError). Logs are not available but we know that it's coming from HTTP client library.

cc @AbelHu

**Comment by AbelHu** [comment]
Did you mean to handle this error in SDK to operate Azure blob storage? The reset error has been handled in [get_token](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb#L1288) and in [http_get_response](
https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb#L1421) in CPI.

**Comment by AbelHu** [comment]
@cppforlife Do you have more details about these two errors? Should CPI check whether the message  contains 'reset' before retrying when OpenSSL::SSL::SSLError or OpenSSL::X509::StoreError occurs?

**Comment by cppforlife** [comment]
can prolly check for "SSL_connect" if there is no other way to determine if its a connection that was not established.

**Comment by AbelHu** [comment]
We will fix this in all ARM REST API calls and then fix it when operating Azure blob storage after azure-storage-sdk fixes the issue https://github.com/Azure/azure-storage-ruby/issues/76

**Comment by pdelagrave** [comment]
Hi @AbelHu 
Was this fixed in a recent version?

**Comment by AbelHu** [comment]
The fix for connections to Azure Resource Manager has been included in the latest Azure CPI releases. The fix for connections to Azure blob storage is still in progress. We planned to include it in next CPI version.

**Comment by AbelHu** [comment]
@pdelagrave It is fixed in this PR #268
