### ISSUE TITLE
CPI does not delete empty availability sets

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry-incubator/bosh-azure-cpi-release#236]
CPI Version: v20

Issue Description:
CPI does not delete empty availability sets so users can find lots empty availability sets in the resource group when redeploying multiple times.

Solution:
Use a temporary file as Mutex, CPI needs to lock before creating an availability set, adding a VM to an availability set or removing a VM from an availability set. If the availability set is empty after removing a VM from it, CPI needs to delete the empty availability set.

**Comment by cppforlife** [comment]
i was chatting with @voelzmo about potentially adding clean_up cpi command that gets executed outside of running any other cpi commands. clean up could remove any left over artifacts. i wouldnt bother adding above proposed logic (file mutex) if we are going to have clean up cpi method. thoughts?

**Comment by AbelHu** [comment]
@cppforlife Since cpi methods are called in parallel, create_vm in one process may pick up one empty avset but clean_up method in another process may wants to delete it. The issue still exists.

**Comment by AbelHu** [comment]
@cppforlife Could BOSH call clean_up method after all cpi commands are executed in one task?
