### ISSUE TITLE
Out-of-the-box deployment of single-vm-cf fails

### ISSUE THREAD

**Issue by guyroth** [cloudfoundry-incubator/bosh-azure-cpi-release#242]
### Issue Details

Hi, 

I'm trying to deploy single-vm-cf.yml, following the standard ARM process described here: https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/guidance.md and getting the error below while running _./deploy_cloudfoundry.sh example_manifests/single-vm-cf.yml_ from inside the bosh VM.

I've tried on different regions (North Europe, East Europe, UK West, US East) and the problem is the same. After some searching online I also tried to raise the VM size of resource_z1 to Standard_D4_v2, but that did not help either.

In another note, the out of the box single-vm-cf.yml template defines a Standard_D1 VM, which is not available on all regions - should probably be documented or changed to Standard_D1_v2.

### Logs (*Please redact all sensitive information in your logs*)

  Started updating instance cf_z1 > cf_z1/8cbc5a15-9be7-4b23-b5c8-b7e4b35b3ce2 (0) (canary). Failed: Action Failed get_task: Task de6aa19d-21d9-4b14-4278-1caf05224f01 result: 1 of 10 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: etcd_metrics_server, nats_stream_forwarder, cloud_controller_clock, etcd, nats, cloud_controller_worker, consul_agent, cflinuxfs2-rootfs-setup, uaa. (00:01:09)

### Repro steps (*if necessary, delete otherwise*)

1. Deploy the [bosh-setup ARM template](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/via-arm-templates/deploy-bosh-via-arm-templates.md)
2. SSH to the bosh VM
3. Run ./deploy_cloudfoundry.sh example_manifests/single-vm-cf.yml

### Account details

Subscription: SAP-SE-AZURE-HCP-CxP-Dev
Resource group: cf-single-vm (UK West)

**Comment by gossion** [comment]
Hi @guyroth , 

I tried to deploy single-vm-cf.yml according to latest [template](https://github.com/Azure/azure-quickstart-templates), I did not see the issue you have reported. My deployment is on North Europe.

So, have you changed the template or the version of cf or diego?
As we [mentioned](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/single-vm-cf.yml#L1), this 'single-vm-cf.yml' are only workable for cf-v238.

Anyway, can you share your template? and tell us the package versions(you can use `bosh deployments` to get the information)?

Thanks

**Comment by guyroth** [comment]
Hi @gossion,

Thank you for looking into this.

I tried deploying again from the latest [bosh-setup template ](https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup) in North Europe and faced the same issue. Note that I tried deploying maybe 7-8 times already, and a single attempt **was** successful.

The only change I did to the template is the in the VM size of the CF VM from Standard_D2 to Standard_D3_v2, no other changes at all.

Here are the versions:
```
+-----------------------+--------------------------+-------------------------------------------------+--------------+
| Name                  | Release(s)               | Stemcell(s)                                     | Cloud Config |
+-----------------------+--------------------------+-------------------------------------------------+--------------+
| single-vm-cf-on-azure | cf/238                   | bosh-azure-hyperv-ubuntu-trusty-go_agent/3262.7 | none         |
|                       | cflinuxfs2-rootfs/1.16.0 |                                                 |              |
|                       | diego/0.1476.0           |                                                 |              |
|                       | garden-linux/0.338.0     |                                                 |              |
+-----------------------+--------------------------+-------------------------------------------------+--------------+
```

Thanks again for your assistance!

Guy

**Comment by gossion** [comment]
Hi @guyroth , in my env I changed VM from Standard_D2 to Standard_D3_v2 but I didn't see the issue. 

Since you can provide the credential, could you please send the credential or the manifest(single-vm-cf.yml) to my mailbox
guwe@microsoft.com? I would like to have a check. 
Thanks

**Comment by gossion** [comment]
The error turns out to be special character '@' in the password making the postgres connectionstring invalid:

```
postgres://ccadmin:fakepassword@@10.0.16.5:5524/ccdb
```
We will add a comment in the deployment script noticing user not to use special character '@' in his/her password. Thanks @guyroth for reporting this issue.

**Comment by guyroth** [comment]
Thanks @gossion for your help!
