### ISSUE TITLE
Managed disk failed to be provisioned

### ISSUE THREAD

**Issue by osharav** [cloudfoundry-incubator/bosh-azure-cpi-release#246]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with Azure CPI :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help us to understand your issue!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 21
BOSH     Version: 260.6
CF       Version: 252
Diego    Version: 1.6.2

### Stemcell
Version: 3312.12
Distro:
  - [X] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [X] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureStack
  - [ ] Others:
- Location: North Central US
- Subscription ID: f1b9567b-8560-44ae-a4fc-741ff0d08a58
- Resource Group Name: rg-m-d

### Issue Details
When trying to run a bosh deployment (any deployment, such as CF) the deployment halts and when trying to cancel we see many disk related errors. In the Azure portal I can see many managed disks which provisioning status = Failed

### Logs (*Please redact all sensitive information in your logs*)
Example error:

Failed creating missing vms > ha_proxy_z1/ead2d554-68cb-4c15-a76d-a9400d22b007 (0): CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<Bosh::AzureCloud::AzureAsynInternalError: http_get_response - http code: 200
x-ms-client-request-id: 4c335b83-bfc8-455a-9751-15d573a85341
x-ms-request-id: 01faf036-6e2a-4fb4-8efb-31dbfd0f1269
x-ms-correlation-request-id: d427e2f7-3f7d-4918-9136-0c42430f78a7
x-ms-routing-request-id: NORTHCENTRALUS:20170307T101258Z:d427e2f7-3f7d-4918-9136-0c42430f78a7
Error message: {
  "startTime": "2017-03-07T10:11:08.4861051+00:00",
  "endTime": "2017-03-07T10:12:54.3982072+00:00",
  "status": "Failed",
  "error": {
    "code": "DiskServiceInternalError",
    "message": "Internal error in disk manager."
  },
  "name": "6decaec7-5446-492a-b37c-74eb7a7c98a7"
}>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1767:in `http_get_response'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1846:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1916:in `http_put'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:282:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:54:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:139:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:117:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'' in 'create_vm' CPI method

### Repro steps (*if necessary, delete otherwise*)
1. Use the new bosh settings to make use of managed disks
2. Run a bosh deployment involving creation of managed disks

Note: We did not try out the migration scenario settings - the deployment was done for the first time.

Regards,
Omer.

**Comment by AbelHu** [comment]
@osharav Could you send more logs about the context of the error? We want to see what requests are sent to Azure when the error occurs. You can send the partial logs to [us](azcfchina@microsoft.com). Please reacted any credentials if the partial logs contain. (BTW: Request id is not credential).

**Comment by osharav** [comment]
I have opened a support request: 117030715417525 and understood from the support engineer that the issue originates from the managed disk feature.
Are you able to access the logs in the support request?

**Comment by AbelHu** [comment]
That is fine. We tried to reproduce the issue but did not reproduce it. Since you have sent logs in the ticket, it should be enough for feature team to investigate it.

**Comment by bingosummer** [comment]
@osharav Any updates from the feature team?

**Comment by osharav** [comment]
Issue has been resolved in Azure infrastructure. Thank you.
