### ISSUE TITLE
Timed out pinging to 7270d4f3-4237-4e8f-8d4a-7ae7c73cf21e after 600 seconds

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/bosh-azure-cpi-release#251]
Hi i am deploy cloud foundry 238 with its respective dependencies with stemcell version  bosh-azure-hyperv-ubuntu-trusty-go_agent (3262.22). I success full deployed bosh-init. I am new to azure i need your help.

Thanks in advance

Abhilash S

**Comment by AbelHu** [comment]
You need to check bosh-agent logs inside the failed VM. If the failed VM has been deleted, you need to update your `bosh.yml` and redeploy your deployment.
  ```
  director:
    debug:
      keep_unreachable_vms: true
  ```

If the VM exists, you can try to ssh to the failed VM with the private key you use in `bosh.yml`. Use `sudo su` with the password `c1oudc0w` and `cd /var/vcap/bosh/log` to check what happened in the logs.

  ```
  cloud_provider:
    ssh_tunnel:
       private_key: YOUR-SSH-PRIVATE-KEY
  ```

If you cannot ssh to the failed VM, you have to delete the VM and mount the OS disk to another Linux VM and find the logs.

**Comment by abhilash07** [comment]
Hi AbelHu thanks for your quick reply, actually i am not able sudo su with password "c1oudc0w" i am also woundering why ?

**Comment by AbelHu** [comment]
Maybe the default password has been removed from the stemcell v3262.22. You can try to add your password in bosh.yml by reference [here](http://www.starkandwayne.com/blog/hardening-the-vcap-users-password-on-bosh-vms/)
```
resource_pools:
    env:
      bosh:
        password: xxxxxx
```

**Comment by AbelHu** [comment]
@abhilash07 Please reopen it if you hit this issue again.
