### ISSUE TITLE
Eval statement presents code injection security vulnerability

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry-incubator/bosh-azure-cpi-release#259]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 22+
BOSH     Version: N/A
CF       Version: N/A
Diego    Version: N/A

### Stemcell
Version: All light stemcells
Distro:
  - [x] Ubuntu
  - [x] CentOS
  - [x] Windows

### Environment
- Azure Environment:
  - [x] Azure
  - [x] AzureChinaCloud
  - [x] AzureUSGovernment
  - [x] AzureStack
  - [ ] Others:
- Location: All
- Subscription ID: All
- Resource Group Name: All

### Issue Details

To support light stemcells, the CPI creates a "dummy" stemcell vhd blob in the stemcell blobstore with metadata attached to reference the marketplace image the light stemcell is based on. The metadata placed on the dummy image to describe the marketplace offering is inserted as a ruby hash object. When a VM is created from the light stemcell image, this metadata is actually evaluated as ruby instead of just parsed as Json or another data format: https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/helpers.rb#L418. This presents a security vulnerability, as a VM offering name/sku/provider/version could arbitrary contents that ends up being valid ruby that gets evaluated.

@pnikonowicz and I are suggesting that instead of storing the image metadata as a ruby hash, it should be stored as Json and decoded as Json instead of evaluated.

**Comment by AbelHu** [comment]
@sunjayBhatia Thanks for your valuable feedback. How do you think if we store image's information as below?

```
"image.offer" => "xxx",
"image.sku" => "xxx",
"image.publisher" => "xxx",
"image.version" => "xxx"
```

**Comment by sunjayBhatia** [comment]
@AbelHu Could we store it as:
```
metadata key: image
metadata value: '{}'

**Comment by AbelHu** [comment]
Thanks, @sunjayBhatia . We will use `to_json` and `JSON.parse`

**Comment by sunjayBhatia** [comment]
Sweet, sounds good! Will close this out
