### ISSUE TITLE
Page links to https://bosh.io/docs/init-azure.html which doesn't exist

### ISSUE THREAD

**Issue by animatedmax** [cloudfoundry-incubator/bosh-azure-cpi-release#26]
This issue was raised in the cf-docs channel of the Cloud Foundry organization on Slack by @Zouuup  

The page htps://github.com/cloudfoundry-incubator/bosh-azure-cpi-release has a link, [initializing a bosh environment on azure] that referes to https://bosh.io/docs/init-azure.html  -- the init-azure.html doesn't appear to exist

**Comment by sedouard** [comment]
I believe @cppforlife is working on that documentation

**Comment by Amit-PivotalLabs** [comment]
It's been a couple months, that link is still broken.  Maybe remove the link until the docs actually exist?

**Comment by AbelHu** [comment]
@cppforlife will update the doc so he can help to answer your question.

**Comment by AbelHu** [comment]
The link works now.
