### ISSUE TITLE
Azure DNS Not Appropriate

### ISSUE THREAD

**Issue by apeschel** [cloudfoundry-incubator/bosh-azure-cpi-release#263]
### Issue Details

The guide recommends Azure DNS: https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/deploy-azuredns/README.md

However, Azure DNS only provides public DNS, and is not well suited for private/internal routes. It seems inappropriate for it to be the recommended form of DNS on Azure.

**Comment by AbelHu** [comment]
@apeschel As the document describes, Azure DNS is only one option. Which DNS server you need to use depends on your environment if you have some specific requirements.
We recommend you to use Azure DNS because it should be most reliable and stable on Azure.
