### ISSUE TITLE
Bump `bosh_cpi` gem

### ISSUE THREAD

**Issue by friegger** [cloudfoundry-incubator/bosh-azure-cpi-release#266]
This not really an issue, just a hint. From the [vendor folder](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/src/bosh_azure_cpi/vendor/package) it looks like you still consume a `1.x` `bosh_cpi`version. Most current version is [2.1.1](https://rubygems.org/gems/bosh_cpi/versions/2.1.1). You might consider upgrading.

The current version includes among other things:
- Returning a `Bosh::Clouds::NotImplemented` error for not implemented API methods to be more consistent with other CPIs
- Fix: Registry passwords can now contain `%`

Kind regards from the OpenStack CPI team

**Comment by bingosummer** [comment]
@friegger and OpenStack CPI team, thank you for your kindly suggestions. We will consider upgrading.

**Comment by bingosummer** [comment]
@friegger 
I notice that AWS CPI has [removed](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/commit/96fce582c93c9bfd9aba2416ae0fe8a8a7191f13) `httpclient` in Gemfile, but OpenStack CPI still keeps it. Could you please share any particular reason?

**Comment by beyhan** [comment]
We don't see any reason for us to keep it because we don't need the `httpclient` directly. We just missed it. Thanks for the point! With the next update we will remove it.

**Comment by AbelHu** [comment]
@friegger Close this after merging the PR #273 .
