### ISSUE TITLE
Could not find any Consul VMs in your BOSH deployment.

### ISSUE THREAD

**Issue by malichishti** [cloudfoundry-incubator/bosh-azure-cpi-release#278]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 
BOSH     Version: 260.5.0
CF       Version: 238
Diego    Version: 0.1476.0

### Stemcell
Version: 3262.7*
Distro:
  - [x ] Ubuntu

### Environment
- Azure Environment:
  - [x] Azure
- Location: Australia East
- Subscription ID: d0e3f648-a679-4610-ae09-5c902e088006
- Resource Group Name: ALICFTest5RG

### Issue Details
I have configured the Dev-box using the guideline provided. I use single-vm-cf.yml. When i try to run generate.exe from diego-windows-release i get "**Could not find any Consul VMs in your BOSH deployment.**"
![image](https://cloud.githubusercontent.com/assets/17155996/26771936/b57c52c0-4a05-11e7-827d-4f8ffbddd548.png)

**Comment by AbelHu** [comment]
@malichishti `single-vm-cf.yml` is outdated. It will not be updated and always use cf-release v238. If you want to learn more about consul VMs, please use `multiple-vm-cf.yml`.

**Comment by malichishti** [comment]
Is there a script i can use to uninstall single-vm-cf.yml from my resource group?

**Comment by AbelHu** [comment]
You can use `bosh delete deployment single-vm-cf-on-azure` to delete the single-vm-cf deployment

**Comment by malichishti** [comment]
@AbelHu can you please inform how many CPU cores should one have to be able to be able to run `multiple-vm-cf.yml` or how many VMs does it try to create?

**Comment by AbelHu** [comment]
@malichishti If you use our template to deployment a multiple cf environment, you will have below VMs
1. devbox: Count: 1, Standard_D1_v2 (1 core)
1. BOSH director VM: Count: 1, Standard_D2_v2 (2 cores)
1. Multiple CF VMS: Count: 19
   Standard_F1 (1 core): 15
  Standard_F2 (2 cores): 3
  Standard_D12_v2 (4 cores): 1
