### ISSUE TITLE
The CPI can't create a VM when an Azure endpoint is momentarily unreachable

### ISSUE THREAD

**Issue by pdelagrave** [cloudfoundry-incubator/bosh-azure-cpi-release#292]
### Versions
CPI      Version: 24 
BOSH     Version: 262.3
CF       Version: 259 (PCF patched, ERT 1.11.5)
Diego    Version: 1.18.1

### Stemcell
Version: 3421.9
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureStack
  - [ ] Others:
- Location: westus
- Subscription ID: 52641c3e-894d-443e-b78b-e00305c8e021
- Resource Group Name: pcf-1-11-to-1-12-azure-pcf-resource-group

### Issue Details
7h into a series of back to back deployments of different bosh deployments the director failed to create a VM:
```
Failed creating missing vms > parser/92c08386-08c1-4bbb-852b-aad46c12c0d3 (0): Unknown CPI error 'Unknown' with message 'Connection refused - connect(2) for "52.190.240.40" port 443' in 'create_vm' CPI method (00:00:19)
```

No special steps are known to reproduce the problem.

A more resilient retry strategy could help solve the problem. That retry strategy could be applied to any calls to the Azure service to avoid having this problem again, this was observed for storage related calls but seems to be fixed: https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/132

Thanks

Pierre Delagrave

**Comment by AbelHu** [comment]
Close it since it was fixed in this PR #298
