### ISSUE TITLE
What is ORGANIZATION parameter and where can I find iit?

### ISSUE THREAD

**Issue by typik89** [cloudfoundry-incubator/bosh-azure-cpi-release#293]
https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/push-demo-app.md
cf target -o "REPLACE_WITH_CLOUD_FOUNDRY_PUBLIC_IP.xip.io_ORGANIZATION" -s "azure"
I can't understand what is ORGANIZATION?

**Comment by bingosummer** [comment]
You don't need to replace the ORGANIZATION. For example, if the public ip is 1.1.1.1, then it should be `1.1.1.1.xip.io_ORGANIZATION`.

When you login CF, you can get the orgs via `cf orgs`.

**Comment by bingosummer** [comment]
@typik89 How is the issue going?

**Comment by bingosummer** [comment]
Closing it due to no response. Feel free to reopen it when you hit the issue again.
