### ISSUE TITLE
Make sure to redact env data

### ISSUE THREAD

**Issue by cdutra** [cloudfoundry-incubator/bosh-azure-cpi-release#296]
Environment data passed to the CPI may contain sensitive data. We did a quick investigation and a few places might be logging sensitive data. Example:

1. Redact `user_data` when logging. As an [example](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/4f8d4d8377864c2e20053335695810d677dee8c8/src/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb#L2166). The `redact_credentials_in_request_body` only redacts the keys `['adminPassword', 'client_secret']`, not anything present in the `user_data` such as `registry_endpoint`.
2. Make sure to redact sensitive data passed through the `env` in the `create_vm`

A tracker story with more info can be found here [#148715311](https://www.pivotaltracker.com/story/show/148715311)

cc @ktchen14

**Comment by AbelHu** [comment]
Close this since it is fixed in this PR #298.
