### ISSUE TITLE
Azure DNS setting error

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/bosh-azure-cpi-release#297]
hi is anyone i set-up Azure dns service for Cloud foundry ha_proxy. I follow the setting process ad following link  (https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/deploy-azuredns).

Next i allocate my ha_proxy public ip to azure dns service.

Next I change the ha_proxy certificate and key same as my dns name.

but i cant able to connect to my api with defined hostname. Should i have to do any more process. Thanks in advance.

**Comment by bingosummer** [comment]
Hi @abhilash07 ,

1. Could you please paste the error message when connecting your api endpoint?
2. Can you check whether your api endpoint can be resolved to your ha_proxy public ip?
3. Did you finish the step [Register Azure DNS](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/deploy-azuredns#2-register-azure-dns)? For example, in the step 2.2, you need to configure the azure dns name in the domain-name service provider.

**Comment by abhilash07** [comment]
This is my error message 
1. cf login -a https://api.mydoamin.com -u admin -p admin
API endpoint: https://api.mydoamin.com
FAILED
Error performing request: Get https://api.mydoamin.com/v2/info: dial tcp: lookup api.mydoamin.com on 127.0.1.1:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

2. Yes my  ha_proxy public ip is resloved well.

3. I think (https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/deploy-azuredns#2-register-azure-dns) i perform up to step 2.1 i miss step 2.2 

Can you please let me knowis there any guide to perform step 2.2. Thanks in advance.

**Comment by bingosummer** [comment]
In step 2.1, you can get four name server domain names. You can run `dig api.mydomain.com @<name-server-domain-name>` to resolve to the public ip. However, without step 2.2, it will fail if you run `dig api.mydomain.com`.

There are no common steps for 2.2. If you domain name is registered in godaddy, you can configure the name server domain name in godaddy's dashboard.

BTW, is `127.0.1.1:53` your private dns server? Why do you use it? Can it resolve your domain name?

**Comment by bingosummer** [comment]
@abhilash07 How is the issue going?

**Comment by abhilash07** [comment]
@bingosummer actually we stopped deployment for a while. we will carry deployment from next week so i will let you know then thanks for your kindness.

**Comment by bingosummer** [comment]
Closing it since there's no update for a long time.
@abhilash07 feel free to re-open it if you have any updates.
