### ISSUE TITLE
There seems to be no network connectivity between the cf-devhost and the main vm for cloudfoundary.

### ISSUE THREAD

**Issue by vinchauhan** [cloudfoundry-incubator/bosh-azure-cpi-release#300]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with Azure CPI :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help us to understand your issue!

### Versions (*please add them if you have more releases for this issue*)
CPI      Version:
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [X] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [X] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureStack
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name: 

### Issue Details
cf login responds with

user@myboshcfvm:~/2048$ cf login -a https://api.xxx.xip.io —skip-ssl-validation -u admin -p c1oudc0w
API endpoint: https://api.xxxx.xip.io
FAILED
Error performing request: Get https://api.xxxx.xip.io/v2/info: dial tcp xxxx:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

Looks like there is no network connectivity between the dev host and the main cf vm. Please update if additional firewall config should done on the Azure portal.

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by AbelHu** [comment]
@vinchauhan Did you use Azure template to deploy it? By default, 443 should have been opened in security group. xip.io is not stable so we suggest you to use a real domain name.

**Comment by bingosummer** [comment]
Closing it since there's no update for a long time.
@vinchauhan please feel free to re-open it if you still hit the issue.
