### ISSUE TITLE
Issues cleaning up NICs + AvailabilitySets after use/errors

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-incubator/bosh-azure-cpi-release#303]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 23
BOSH     Version: 261.4

### Stemcell
Version: 3421.4
Distro:
  - Ubuntu
 
### Environment
- Azure Environment:
  - [x ] Azure
 - Location: east US

### Issue Details

We saw a strange issue the other day. Our compilation VMs were using auto-created availability sets, which never got cleaned up. As a result we eventually ran out of availability set quota (at 800). After that, compilation VM creation hung for a *really* long time. This went on without being noticed for a decent amount of time, and bosh ate up a bunch of IPs in the dynamic pool, trying to create new compilation VMs. The network interfaces also never got torn down after the failure to create the compilation VM/availability set, and then the CPI was unable to create new compilation VMs after resolving the availability-sets, as the IPs were still in use from azure's perspective.

Seems like there are three possible bugs here:

-  Lack of a shorter (10-20 mins) timeout when failing to create a compilation VM due to issues creating availability sets
- Not cleaning up auto-generated availability sets for compilation VMs when compilation is over
- Not cleaning up NICs from Azure when compilation VM creation failed

### Repro steps (*if necessary, delete otherwise*)
1. Deploy a BOSH + deployment to azure, using auto-genrated availability sets
2. Create as many Availability Sets as you're allowed to via the azure CLI, before hitting quota issues, then delete one
3. Try to compile a boshrelease (allow for only one IP in the dynamic pool for the compilation network)
4. Remove the extra Availability Sets
5. Compile again

**Comment by geofffranks** [comment]
cc/ @cppforlife @dennisjbell @thomasmmitchell

**Comment by AbelHu** [comment]
Close this since it is fixed in #306.
