### ISSUE TITLE
This is not error!! A query about Configuring VM Scale Sets for Cloud Foundry Deployment

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/bosh-azure-cpi-release#304]
Hi everyone thanks for your Documentation.  Is there a way to configure VM scale sets a "VM auto scaling service" to cloud foundry deployment.

I Configure Availability sets on my cloud foundry, but i think it is good for production deployment  to configure VM scale sets on Cloud foundry. Thanks in advance.

**Comment by AbelHu** [comment]
@abhilash07 We are glad to hear that you are interested in Azure VM scale sets. We discussed this solution last year. Considering current BOSH design and scenarios, we would not enable VM scale sets in cloud foundry.

**Comment by abhilash07** [comment]
@AbelHu thanks for quick response, yes you're right Bosh design is complicate to implement auto scaling.
