### ISSUE TITLE
Ruby 2.4.0 doesn't like the no_proxy env

### ISSUE THREAD

**Issue by dwallraff** [cloudfoundry-incubator/bosh-azure-cpi-release#314]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 27
BOSH     Version: 263
CF       Version: N/A
Diego    Version: N/A

### Stemcell
Version: 3445.7
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
  - [ ] Others:
- Location: (e.g. East US) westeurope
- [ ] Use Managed Disks

### Issue Details
v27 of the cpi uses v2.4.0 of ruby which doesn't respect no_proxy correctly.
We temporarily fixed this by downgrading to v24 of the cpi

### Logs (*Please redact all sensitive information in your logs*)
[cpiCmdRunner] 2017/09/14 07:54:14 DEBUG - Rescued Bosh::Clouds::CloudError: http_get_response - #<Bosh::Clouds::CloudError: get_token - #<IPAddr::InvalidAddressError: invalid address>
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/ipaddr.rb:563:in `in6_addr'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/ipaddr.rb:500:in `initialize'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/ipaddr.rb:518:in `new'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/ipaddr.rb:518:in `coerce_other'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/ipaddr.rb:174:in `include?'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/uri/generic.rb:1541:in `block in find_proxy'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/uri/generic.rb:1530:in `scan'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/uri/generic.rb:1530:in `find_proxy'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/net/http.rb:1061:in `proxy_uri'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/net/http.rb:1048:in `proxy?'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/net/http.rb:893:in `connect'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/net/http.rb:876:in `start'
/home/pcfadm/.bosh/installations/9a6ca11a-7830-42d0-5092-730ca93b3dd7/packages/ruby_azure_cpi/lib/ruby/2.4.0/net/http.rb:1407:in `request'

**Comment by AbelHu** [comment]
@dwallraff It seems like to be a bug of Ruby 2.4.1. And it has been fixed in 2.4.2 (14 Sep 2017). We will upgrade ruby version to 2.4.2. Please reference
1. [Proxy Error On Ruby 2.4.0](http://ermaker.github.io/blog/2017/02/06/proxy-error-on-ruby-2.4.0.html),
2. `merge revision(s) 57359: [Backport #13442]` in [commit logs](https://github.com/ruby/ruby/compare/v2_4_1...v2_4_2) for [Ruby 2.4.2](https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/).
