### ISSUE TITLE
VM cid changed for bosh vms endpoint

### ISSUE THREAD

**Issue by pritishmishra** [cloudfoundry-incubator/bosh-azure-cpi-release#315]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

### Release Versions
CPI      Version: 26
BOSH     Version: 263
CF       Version: 271
Diego    Version: 1.25.1

### Stemcell
bosh-azure-hyperv-ubuntu-trusty-go_agent  Version: 3445.2
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
  - [ ] Others:

### Issue Details
Earlier, up until now, when we try to get response of `GET /deployments/{name}/vms` endpoint of bosh, we used to get a `{cid: CID_NAME}` in the response. However, since the last week, (after the CPI version: 26), we observe that the response has changed to `{cid: agent_id: AGENT_ID_NAME; resource_group_name: RESOURCE_GROUP_NAME}`. This is breaking all our code and hence, operations, since, this is not the format of response we were expecting.

Is this a bug from bosh/bosh-cpi 's end? Is such a response correct/expected?
Why has this response changed from the earlier one?

### Reproduction steps
1. Try hitting the bosh vms endpoint and you can check the cid in the response

**Comment by AbelHu** [comment]
@pritishmishra It is by design to support multiple resource groups. Sorry for the inconvenience which is caused by the VM CID's change.

In earlier versions before v26, CPI always use a default resource group to create all resources.
To support multiple resource groups, CPI needs to use cid to store resource group name for delete_vm, attach_disk, etc. Please see more details in [instance_id.rb](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/instance_id.rb).

**Comment by pritishmishra** [comment]
@AbelHu Thanks for the response.
Actually, the change was unexpected for us and hence, we were not prepared with the corresponding changes in the code. Are there usually any announcements made before/after such changes? 

I will be closing this issue, since it is clear why the change was made and that this is not a bug in any way. Hope, this parameter doesn't change again and there is some announcement, before it changes.

**Comment by pritishmishra** [comment]
Also, I needed one other clarification. For Azure, the agent_id is same as the vm cid and in the vm cid parameter also, agent_id is appearing. But, for all other IaaS, vm cid and agent_id are different.
Can we be sure that for Azure, the vm cid will always be the same as agent_id or is it likely to change in the future?

**Comment by AbelHu** [comment]
@pritishmishra From our design, the instance id (BOSH terms) can be different from the VM name and we use agent_id as VM name directly. So I think that it should not be changed in future. And now we understand that you may rely on this so we would keep it in our mind.

**Comment by cppforlife** [comment]
> Can we be sure that for Azure, the vm cid will always be the same as
agent_id or is it likely to change in the future?

i would be very careful here in terms of relying on cids. cloud ids are
meant to be opaque to users outside of cpi. can you elaborate why you need
to decode details of a cloud id?

**Comment by pritishmishra** [comment]
@cppforlife The cloud id is essentially vm name for us (vm name on Azure's end). And we need to find this vm name for our operations.

**Comment by cppforlife** [comment]
> And we need to find this vm name for our operations.

what kind of actions are you performing?
