### ISSUE TITLE
CI Break - No such file azure.yml.erb

### ISSUE THREAD

**Issue by sedouard** [cloudfoundry-incubator/bosh-azure-cpi-release#32]
No such file or directory @ rb_sysopen - /tmp/build/fc9093cb-64ae-403c-60c3-9ef6ee836ec2/bosh/bat/templates/azure.yml.erb.

@AbelHu this file doesn't exist in https://github.com/AbelHu/bosh-acceptance-tests at master. Should we still be pointing to this repo?

https://bosh-azure-cpi.ci.cf-app.com/pipelines/azure-cpi/jobs/bats-ubuntu/builds/1

**Comment by sedouard** [comment]
@AbelHu its likely due to this https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/commit/8b7efd232146c3a28ddf025056e6d0592da01208

**Comment by AbelHu** [comment]
@sedouard The new [PR](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/pull/34) has bee created.

**Comment by AbelHu** [comment]
The PR is merged.
