### ISSUE TITLE
CI - Azure Ruby SDK Client Side timeout fix

### ISSUE THREAD

**Issue by sedouard** [cloudfoundry-incubator/bosh-azure-cpi-release#33]
Uploading page blobs outside of azure reliability is difficult due to the fact that the ruby sdk doesn't have  a client side timeout.

The CI Infrastructure is running in AWS and needs this in order to be reliable and avoid failures [like this one](https://bosh-azure-cpi.ci.cf-app.com/pipelines/azure-cpi/jobs/lifecycle/builds/2)

**Comment by AbelHu** [comment]
This bug is related to the bug [334](https://github.com/Azure/azure-sdk-for-ruby/issues/334) in azure-sdk-for-ruby. After it is fixed, CPI will use the new sdk.
