### ISSUE TITLE
delete_disk_reference fails

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry-incubator/bosh-azure-cpi-release#339]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details

`bosh cck --resolution delete_disk_reference --resolution delete_vm_reference` on azure to delete stale disk references and are getting the error

### Logs (*Please redact all sensitive information in your logs*)

```
Task 210 | 18:52:49 | Scanning 11 persistent disks: Looking for inactive disks (00:00:06)
                    L Error: CPI error 'Bosh::Clouds::CloudError' with message 'This function should only be called for unmanaged disks' in 'has_disk' CPI method
Task 210 | 18:52:55 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'This function should only be called for unmanaged disks' in 'has_disk' CPI method
```

### Repro steps (*if necessary, delete otherwise*)
1. Delete a vm with persistent disk
1. run `bosh cck --resolution delete_disk_reference --resolution delete_vm_reference`

**Comment by bingosummer** [comment]
1. Could you please run "bosh task 210 --debug > 210.log" to collect the task debug log and send it to the email azcfengg@microsoft.com?
2. Are you using azure managed disks? You can check the property `use_managed_disks` in bosh.yml.
3. What's the CPI version?

**Comment by gossion** [comment]
issue happens at this [line](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/v32/src/bosh_azure_cpi/lib/cloud/azure/cloud.rb#L237) in cloud.rb and [line](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/v32/src/bosh_azure_cpi/lib/cloud/azure/disk_manager.rb#L83) in disk_manager.
After a managed disk is removed, `has_disk?` will also check if it has a unmanaged disk with the same diskid.

**Comment by bingosummer** [comment]
@tinygrasshopper 
@gossion has fixed the issue, and the fix is included in the version [`v34`](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/releases/tag/v34).
Could you please try it and let us know if you have any issues?

**Comment by bingosummer** [comment]
Closing as stale, feel free to mention us and have it re-opened.
