### ISSUE TITLE
ERROR -- DirectorJobRunner: Action Failed get_task: Task b5b3835f-b379-44c0-6f25-9ad693e5be0d result: Persistent disk with volume id '........' could not be found -- in disk attach -- in Azure

### ISSUE THREAD

**Issue by sauravmndl** [cloudfoundry-incubator/bosh-azure-cpi-release#341]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 
BOSH     Version: 263.3.0
CF       Version: 278
Diego    Version:

### Stemcell
Name: bosh-azure-hyperv-ubuntu-trusty-go_agent
Version: 3468
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
  - [ ] Others:
- Location:  West Europe
- Subscription ID:  
- Resource Group Name: 
- [x] Use Managed Disks

### Issue Details
I am facing above issue when doing bosh attach of disk to vm from BOSH CLI. But when I am doing the disk attachment manually it works.
Command: 
bosh -e bosh-my-env -d my-deployment-name attach-disk blueprint_z1/06457717-5e63-4d1a-94d0-671fb59cdd4e  disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sample-azure-dev1

### Logs (*Please redact all sensitive information in your logs*)
[2017-11-27 18:33:11 #13053] [task:869] ERROR -- DirectorJobRunner: Action Failed get_task: Task b5b3835f-b379-44c0-6f25-9ad693e5be0d result: Persistent disk with volume id 'disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sample-azure-dev1' could not be found /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:301:inhandle_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:356:in handle_message_with_retry' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:58:inmethod_missing'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:412:in get_task_status' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:206:inwait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:376:in send_message' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:106:inmount_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/disk_manager.rb:169:in mount_disk' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/disk_manager.rb:78:inattach_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:78:in handle_new_disk' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:31:inblock in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:136:in _transaction' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:110:inblock in transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in block in synchronize' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:inhold'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in synchronize' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:99:intransaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/transactor.rb:5:in block in retryable_transaction' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:inblock in retryer'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in loop' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:inretryer'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/common.rb:118:in retryable' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/transactor.rb:4:inretryable_transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:29:in perform' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:96:inperform_job'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:32:in block in run' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:inwith_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:32:in run' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:inperform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in block in perform' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:85:inblock (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in block in spawn_threadpool' /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:inblock in create_with_logging_context'
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000094s) SELECT NULL
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000237s) SELECT * FROM "tasks" WHERE ("id" = 869) LIMIT 1
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000133s) SELECT NULL
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000063s) BEGIN
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000414s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-11-27 18:33:11.981151+0000', "description" = 'attach disk ''disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sample-azure-dev1'' to ''blueprint_z1/c6df4272-3efc-44ee-a186-ce8101fb12db''', "result" = 'Action Failed get_task: Task b5b3835f-b379-44c0-6f25-9ad693e5be0d result: Persistent disk with volume id...', "output" = '/var/vcap/store/director/tasks/869', "checkpoint_time" = '2017-11-27 18:32:47.015496+0000', "type" = 'attach_disk', "username" = 'admin', "deployment_name" = 'service-fabrik-1047-a8ff8ce0-9577-4506-be04-3483ddd2f2f2', "started_at" = '2017-11-27 18:30:46.968654+0000', "event_output" = '{"time":1511807591,"error":{"code":450001,"message":"Action Failed get_task: Task b5b3835f-b379-44c0-6f25-9ad693e5be0d result: Persistent disk with volume id ''disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sf-azure-dev1'' could not be found"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 869)
D, [2017-11-27 18:33:12 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.025650s) COMMIT
I, [2017-11-27 18:33:12 #13053] [] INFO -- DirectorJobRunner: Task took 2 minutes 25.041717989999995 seconds to process.

Task 869 error

Capturing task '869' output:
Expected task '869' to succeed but state is 'error'

Exit code 1`

**Comment by gossion** [comment]
Hi @sauravmndl ,

I did not see error `Bosh::Clouds::CloudError: Invalid data disk name (version 1)` in your debug log, can you attach more log? I believe there should be some backtrace log about this error message in your debug log.

And it looks like disk `disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sf-azure-dev1 ` can not be found, did you delete it manually?

**Comment by gossion** [comment]
I reproduced a similar issue,  and filed a new ticket at [bosh](https://github.com/cloudfoundry/bosh/issues/1857) since sauravmndl's ticket (# 1841) was already closed.
@sauravmndl , can you check your debug log to see if it is the same issue with yours?

**Comment by sauravmndl** [comment]
No the disk is there.

**Comment by gossion** [comment]
@sauravmndl , can you attach some more logs containing `Bosh::Clouds::CloudError: Invalid data disk name (version 1)` from your debug log? 
I did not see the `get_task: ... result: Persistent disk with volume id '...' could not be found` in my debug log, it still can be a different issue.

**Comment by gossion** [comment]
@sauravmndl , I closed issue https://github.com/cloudfoundry/bosh/issues/1857.
`;` is a sh seperator, can you wrap your disk cid with `'` or `"` and retry?
```
bosh -e bosh-my-env -d my-deployment-name attach-disk blueprint_z1/06457717-5e63-4d1a-94d0-671fb59cdd4e 'disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sample-azure-dev1'
```

let me know your result.

**Comment by sauravmndl** [comment]
Sure. Will try.

**Comment by sauravmndl** [comment]
Hi @gossion 

We are facing one infra issue. Once solved would try and let you know.

Thanks
Saurav

**Comment by bingosummer** [comment]
Closing as stale, feel free to mention us and have it re-opened.
