### ISSUE TITLE
Azure Stack: Wrong default for Availability Set Values fault and update domain

### ISSUE THREAD

**Issue by ClaudiaBaur** [cloudfoundry-incubator/bosh-azure-cpi-release#350]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 29
BOSH     Version:"264.3.0"
CF       Version:
Diego    Version:

### Stemcell
Version:3468.5
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [x] AzureStack
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details
When using availability sets and not specifying concrete values for the amount of update and fault domains in the bosh manifest, the default from Azure is used on Azure Stack (3 fault, 5 update domains).
Azure Stack is limited to 1 update and 1 fault domain, so that only these values can be used for availability sets on Azure Stack.
When specifying 
    cloud_properties:
+     platform_fault_domain_count: 1
+     platform_update_domain_count: 1
all works fine.
When not specifying any characteristics in the bosh manifest, an availability set with 3 fault and 5 update domains is created. When advising more then 1 VM to this availability set, Azure Stack runs into trouble.

**Comment by bingosummer** [comment]
Thanks for raising the issue.

Two options:
* Option 1: Hard-code the default value to `1` for Azure Stack. Same behavior as Azure.
* Option 2: Add two new properties `platform_fault_domain_count` and `platform_update_domain_count` for Azure Stack in [CPI global configuration](http://bosh.io/docs/azure-cpi.html#global). You can set the default values through them.

Which option do you prefer?

**Comment by ClaudiaBaur** [comment]
Hi Bin,
For me both options sound fine. Option 2 is more future-oriented as these limitations of Azure Stack might change over time.
Thanks so much for your support
