### ISSUE TITLE
Enabling encryption of root volume on Azure

### ISSUE THREAD

**Issue by yjayaraman-pivotal** [cloudfoundry-incubator/bosh-azure-cpi-release#363]
### Stemcell
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [x] AzureChinaCloud
  - [x] AzureUSGovernment
  - [x] AzureGermanCloud
  - [ ] AzureStack
  - [x ] Others: AzureUSGovernment
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details
I want to encrypt stemcells with a user provided key. How would I do that on Azure

**Comment by mxplusb** [comment]
@yjayaraman-pivotal would you be able to provide some details for this feature request? I have some outstanding questions.

* Will Azure SSE resolve this feature?
* Is there a specific Azure feature you have in mind?
* Does this feature need to support a 3rd Party solution? i.e., Gemalto, etc.
* Azure China, Azure Government, and Azure Germany are sovereign clouds with potentially separate features. What is the minimum location requirement you envision for this feature?
* What do you envision the user experience for this feature to be? i.e., where do you pass the key to decrypt the disk?
* Is key rotation needed?

//cc @NingKuang

**Comment by cppforlife** [comment]
> I want to encrypt stemcells with a user provided key. How would I do that on Azure

i would like to elaborate a bit more on this feature request (if i understood it correctly). the ask is to be able to encrypt root disk, ephemeral disk and persistent disk (all block devices) transparently. to draw analogies, gcp does this transparently i believe for all disks [1]. aws asks users to specify encryption attribute (encrypted=true) and allows provide a custom encryption key [2].

> Will Azure SSE resolve this feature?

is azure sse apply to block devices (ie persistent disks)?

> Does this feature need to support a 3rd Party solution? i.e., Gemalto, etc.

as long as this is done at the iaas layer (operating system does not know anything about it), i dont think it's important who does it.

[1] https://cloud.google.com/security/encryption-at-rest/
[2] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html

**Comment by yjayaraman-pivotal** [comment]
Thanks Dimitriy for providing more clarity. You understood my question
perfectly.



   - Will Azure SSE resolve this feature?

*As long as the Azure SSE will allow boot volumes to be encrypted for
stemcells (Azure documentation states that Azure Disk Encryption is only
available for Gallery VMs, where does stemcells fall in that category). *

   - Is there a specific Azure feature you have in mind?

*Azure Disk Encryption for Windows and Linux*

   - Does this feature need to support a 3rd Party solution? i.e., Gemalto,
   etc.

*Not necessary *

   - Azure China, Azure Government, and Azure Germany are sovereign clouds
   with potentially separate features. What is the minimum location
   requirement you envision for this feature?

*AzureUSGovernment*

   - What do you envision the user experience for this feature to be? i.e.,
   where do you pass the key to decrypt the disk?

*Using bosh repack-stemcell command or as a cloud property in cloud-config*


   - Is key rotation needed?

*Yes*

Yadhav Jayaraman | Senior Platform Architect, Northeast | Pivotal
c: 314-960-3013 | e: yjayaraman@pivotal.io

Check Out Pivotal! <http://www.pivotal.io/>

**Comment by mxplusb** [comment]
//cc @jastev

**Comment by cppforlife** [comment]
> As long as the Azure SSE will allow boot volumes to be encrypted for
stemcells

stemcells themselves mostly do not carry any customer specific data. we mostly care about disks that are created dynamically like ephmeral and persistent disks (of course if possible it's nice to encrypt root disk (ie stemcell) as well). eph and persistent disk is where customer data resides mostly.

stemcells are not Gallery VMs. data disks are not either.

> *Using bosh repack-stemcell command or as a cloud property in cloud-config*

in the ideal case we turn this on as a deafult in the cpi for all disks. similarly to what we've done in aws cpi.

**Comment by bingosummer** [comment]
[SSE doesn't support user-provided keys for now](https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption#frequently-asked-questions-about-storage-service-encryption-for-data-at-rest). Azure is working on this feature. We will check the timeline of the feature.

* For unmanaged disks
  * customers need to enable SSE in the storage account setting. All the disks (root disk, ephemeral disk and persistent disk) in this storage account will be encrypted.
  * If SSE is enabled after the VM is created, only the new data written to existing disks are encrypted. So, you need to enable SSE at the beginning.
* For managed disks
  * SSE is [enabled by default](https://azure.microsoft.com/en-us/blog/azure-managed-disks-sse/).

**Comment by yjayaraman-pivotal** [comment]
Sorry for my confusion but the doc 
https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption#frequently-asked-questions-about-storage-service-encryption-for-data-at-rest seems to indicate that SSE is for blob storage and Azure Disk Encryption is for IaaS VMs. Could you please confirm if turning on SSE would mean  the boot disk is encrypted.

**Comment by bingosummer** [comment]
@yjayaraman-pivotal 
Yes, I think so. After turning on SSE, all the new written data to the storage account will be encrypted. In your case, you need to enable SSE before uploading the stemcell. Then the stemcell and the root disk will be encrypted.

**Comment by bingosummer** [comment]
The encryption key is fully managed by Azure and the encryption is transparent. Just to confirm, in this case, do you still need the feature "user-provided key"?

**Comment by yjayaraman-pivotal** [comment]
Yes, 'user-provided key' would be needed, I hear that Microsoft is planning on releasing this capability pretty soon.

**Comment by cwsteve2117** [comment]
@bingosummer any update on what Azure will support users providing their own key for encrypting Azure storage? Many of our customers on Azure are asking for this feature.

**Comment by bingosummer** [comment]
The feature of customer managed keys is in preview.
https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption-customer-managed-keys

**Comment by cwsteve2117** [comment]
@bingosummer will there be a need to make changes to the CPI with the SSE BYOK feature you mentioned? Is the end-to-end experience of getting encryption of all disks something that is on your roadmap for Azure and the CPI? Thanks!

**Comment by bingosummer** [comment]
@cwsteve2117 
Recently, I followed the doc to enable SSE BYOK feature, but I got an error `The Server was unable to complete your Request` in the step ["Enable encryption with customer-managed keys"](https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption-customer-managed-keys). I've opened a support ticket to Azure. After fixed, I'll investigate whether there's a need to make changes to the CPI.

**Comment by bingosummer** [comment]
From Azure support, the fix for the error `The Server was unable to complete your Request` will roll out worldwide in next few weeks.

**Comment by bingosummer** [comment]
The fix is already rolled out. For now, no need for code change in CPI.

**Comment by Amit-PivotalLabs** [comment]
Hi @bingosummer 

I have a couple questions:

1. How would key rotation work here (whether it's BYOK or using a key provided by Azure)?
2. You mentioned this SSE feature would apply to all disks (root, ephemeral, and persistent) but [this doc](https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption?toc=%2fazure%2fstorage%2fblobs%2ftoc.json) on SSE makes it sound like disk encryption is something totally different:

> **Q: How is this different from Azure Disk Encryption?**
> A: Azure Disk Encryption is used to encrypt OS and data disks in IaaS VMs. For more information, see the Storage security guide.

So I'm not clear, are they the same or different?

**Comment by bingosummer** [comment]
@Amit-PivotalLabs 

For Azure-managed key, I am afraid there's no way to rotate it. For BYOK, I didn't find an azure doc which mentions the rotation. I did a test myself, I think you can rotate the key with “New Version” function in the Key vault.
![1](https://user-images.githubusercontent.com/4787647/39792994-fc3e4e1e-5375-11e8-93cf-41ce95026bc7.jpg)


SSE and ADE are different. See https://github.com/MicrosoftDocs/azure-docs/issues/7147#issuecomment-381229970

Unfortunately, ADE is not supported in CF because ADE doesn't support custom Linux images (stemcell). https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-faq#can-i-apply-azure-disk-encryption-on-my-custom-linux-image

**Comment by Amit-PivotalLabs** [comment]
Thanks @bingosummer! I guess my question with regards to rotation is more around how does it work end to end.  So you can create a new version in Azure Key Vault.   But what then triggers re-encryption of all the data at rest, to actually use the new key?

**Comment by bingosummer** [comment]
@Amit-PivotalLabs 

I sent an email to Azure Key Vault PG with the following questions, and got the response. Additonally, I also file an issue in Azure docs to look for an official recommendation for key rotation.

Q: How to do the key rotation? Can I simply select another key from the key vault? Does it mean the previous written data are encrypted by the old key and the new written data are encrypted by the new key?
A: You can call KV API to rotate the key. SSE uses 3 level hierarchy of keys. The AEK (Account Encryption Key) is wrapped using the CMK (Customer Managed Key) in AKV. For every write we generate a derived DEK (Data Encryption key) from AEK. So when you rotate the key in AKV, a new key simply encrypts AEK. Hope that helps!

**Comment by Amit-PivotalLabs** [comment]
Got it, thanks!

**Comment by cwsteve2117** [comment]
@bingosummer, just to confirm, BYOK and applying to the storage with SSE is transparent to PCF? PCF doesn't need the key or the rotation updates, correct? That's all managed by the operators on the Azure side?
