### ISSUE TITLE
Azure CPI fails to create managed disk if blob storage account exists

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry-incubator/bosh-azure-cpi-release#371]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 35
BOSH     Version: 264.7
CF       Version: none so far
Diego    Version: none so far

### Stemcell
Version: 3468.21
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: Eu North
- [x] Use Managed Disks

### Issue Details

We have used terraform to create a storage account and want to use managed disks for bosh. Unfortunately, bosh falls over the Blobs storage account. After removing the blobs storage account, the stemcell can be uploaded and a storage account for the managed disks is created 

### Logs (*Please redact all sensitive information in your logs*)

creating stemcell (bosh-azure-hyperv-ubuntu-trusty-go_agent 3468.21):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"has_stemcell_table?: #\u003cAzure::Core::Http::HTTPError:70349862054220 @http_response: #\u003cAzure::Core::Http::HttpResponse:0x00007ff735135360 @http_response=#\u003cFaraday::Response:0x00007ff7351353d8 @on_complete_callbacks=[], @env=#\u003cFaraday::Env @method=:get @body=\"\u003c?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?\u003e\u003cerror xmlns=\\\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\\\"\u003e\u003ccode\u003eNotImplemented\u003c/code\u003e\u003cmessage xml:lang=\\\"en-US\\\"\u003eThe requested operation is not implemented on the specified resource.\\nRequestId:fd5b3223-0002-0034-057c-9e644d000000\\nTime:2018-02-05T12:22:56.2118378Z\u003c/message\u003e\u003c/error\u003e\" @url=#\u003cURI::HTTPS https://xxx.table.core.windows.net/Tables('stemcells')\u003e @request=#\u003cFaraday::RequestOptions open_timeout=60\u003e @request_headers={\"User-Agent\"=\u003e\"BOSH-AZURE-CPI; Azure-Storage/0.12.3-preview (Ruby 2.4.2-p198; MacOS darwin17.4.0)\", \"x-ms-date\"=\u003e\"Mon, 05 Feb 2018 12:22:56 GMT\", \"x-ms-version\"=\u003e\"2015-04-05\", \"DataServiceVersion\"=\u003e\"1.0;NetFx\", \"MaxDataServiceVersion\"=\u003e\"3.0;NetFx\", \"Content-Type\"=\u003e\"application/atom+xml; charset=utf-8\", \"x-ms-client-request-id\"=\u003e\"50aeafa2-7221-4f50-85ef-6b2d22689e78\", \"Content-Length\"=\u003e\"0\", \"Authorization\"=\u003e\"SharedKey xxx:ibs7nk78FcAsstbMwikM7BjNPi2CQAhJgckb46dd1as=\"} @ssl=#\u003cFaraday::SSLOptions verify=true\u003e @response=#\u003cFaraday::Response:0x00007ff7351353d8 ...\u003e @response_headers={\"cache-control\"=\u003e\"no-cache\", \"transfer-encoding\"=\u003e\"chunked\", \"content-type\"=\u003e\"application/xml;charset=utf-8\", \"server\"=\u003e\"Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0\", \"x-ms-request-id\"=\u003e\"fd5b3223-0002-0034-057c-9e644d000000\", \"x-ms-version\"=\u003e\"2015-04-05\", \"x-content-type-options\"=\u003e\"nosniff\", \"date\"=\u003e\"Mon, 05 Feb 2018 12:22:55 GMT\", \"connection\"=\u003e\"close\"} @status=501 @reason_phrase=\"Not Implemented\"\u003e\u003e, @uri=#\u003cURI::HTTPS https://xxx.table.core.windows.net/Tables('stemcells')\u003e\u003e, @uri: #\u003cURI::HTTPS https://xxx.table.core.windows.net/Tables('stemcells')\u003e, @status_code: 501, @type: \"NotImplemented\", @description: \"The requested operation is not implemented on the specified resource.\\nRequestId:fd5b3223-0002-0034-057c-9e644d000000\\nTime:2018-02-05T12:22:56.2118378Z\"\u003e\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/retry_policy.rb:48:in `call'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:104:in `block in with_filter'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/signer_filter.rb:28:in `call'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/signer_filter.rb:28:in `call'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:104:in `block in with_filter'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/service.rb:36:in `call'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/filtered_service.rb:34:in `call'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/signed_service.rb:41:in `call'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-storage-0.12.3.preview/lib/azure/storage/service/storage_service.rb:53:in `call'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-storage-0.12.3.preview/lib/azure/storage/table/table_service.rb:112:in `get_table'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/storage_account_manager.rb:208:in `has_stemcell_table?'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/storage_account_manager.rb:168:in `block in default_storage_account'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/storage_account_manager.rb:167:in `each'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/storage_account_manager.rb:167:in `find'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/storage_account_manager.rb:167:in `default_storage_account'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:12:in `initialize'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:635:in `new'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:635:in `init_azure'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:28:in `initialize'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/bin/azure_cpi:31:in `new'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/bin/azure_cpi:31:in `block in \u003ctop (required)\u003e'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:80:in `run'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/bosh_azure_cpi/bin/azure_cpi:39:in `\u003ctop (required)\u003e'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/bin/bundle:30:in `block in \u003cmain\u003e'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'\n/Users/shalah/.bosh/installations/bee4ce52-8469-4ec2-5fed-026f08c571c4/packages/ruby-2.4-r3/bin/bundle:22:in `\u003cmain\u003e'","ok_to_retry":false}

### Repro steps (*if necessary, delete otherwise*)
1. Create a blob storage account (and make sure it the only storage account of the resource group)
2. bosh create-env
3.
4.
5.

**Comment by bingosummer** [comment]
Thanks for reporting the issue.
I assume the blobs storage account is the storage account whose account kind is "blob storage". If so, it doesn't support the table service. You need to create a storage account whose account kind is "general purpose".

**Comment by schmidtsv** [comment]
I used the 'use managed disks' flag in the CPI, so I assumed this will be done by the CPI (which it does after I remove the blob store account, deploy, then recreate it).

**Comment by bingosummer** [comment]
Can you show me the terraform code of creating the storage account?

**Comment by schmidtsv** [comment]
resource "azurerm_storage_account" "cc-blobstores" {
  name                     = "azuremindsphereblobs"
  resource_group_name      = "${azurerm_resource_group.xxx-staging-group.name}"
  location                 = "North Europe"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "BlobStorage"
  enable_blob_encryption   = "true"

  tags {
    environment = "staging"
  }
}

resource "azurerm_storage_container" "buildpacks" {
  name                  = "azure-staging-buildpacks"
  resource_group_name   = "${azurerm_resource_group.xxx-staging-group.name}"
  storage_account_name  = "${azurerm_storage_account.cc-blobstores.name}"
  container_access_type = "private"
}

resource "azurerm_storage_container" "resources" {
  name                  = "azure-staging-resources"
  resource_group_name   = "${azurerm_resource_group.xxx-staging-group.name}"
  storage_account_name  = "${azurerm_storage_account.cc-blobstores.name}"
  container_access_type = "private"
}

resource "azurerm_storage_container" "packages" {
  name                  = "azure-staging-packages"
  resource_group_name   = "${azurerm_resource_group.xxx-staging-group.name}"
  storage_account_name  = "${azurerm_storage_account.cc-blobstores.name}"
  container_access_type = "private"
}

resource "azurerm_storage_container" "droplets" {
  name                  = "azure-staging-droplets"
  resource_group_name   = "${azurerm_resource_group.xxx-staging-group.name}"
  storage_account_name  = "${azurerm_storage_account.cc-blobstores.name}"
  container_access_type = "private"
}

**Comment by bingosummer** [comment]
Thanks @schmidtsv . From the terraform template, the storage account's `account_kind` is `BlobStorage`.

**The root cause analysis:**
Azure CPI needs a default storage account to store stemcells (page blobs). So, even in the managed disk scenario, CPI still needs a storage account. If not existed, CPI will create one. For the unmanaged disks scenario, CPI needs a table `stemcells` in the storage account to store metadata to support the [multiple storage account feature](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/deploy-cloudfoundry-with-multiple-storage-accounts).

So, the default storage account has to be a **general-purpose** storage account, because:
* [blob storage accounts support only block and append blobs, and not page blobs](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-options#blob-storage-accounts)
* blob storage accounts doesn't support table

Initially, there is a blob storage account in your resource group. CPI tries to use it as the default storage account and failed.

**The following two options are suggested:**
* Option 1: Create a general-purpose v1 storage account (only v1 is tested for now. We have a plan to test the general-purpose v2 storage account), and then retry to deploy it.
* Option 2: Don't create any storage accounts and let CPI create it for you. But in this case, CPI won't create the container `buildpacks`, etc.

**Remaining works:**
* CPI should avoid using a blob storage account as the default account.
* Support general-purpose v2 storage account. The main work is to verify whether v2 works.

**Comment by schmidtsv** [comment]
So you are saying that I cannot create any storage accounts if I want bosh to use managed disks, not even for things like CF-blobs etc? Shouldn't the CPI detect that it cannot use the Store, see no others are there and then create one? Sounds like a more intuitive behaviour. 
I have another question. Am I correct in the assumption that for bosh the default storage account is always the oldest, aka I can get one created and then add the blob storage account?

**Comment by bingosummer** [comment]
> I have another question. Am I correct in the assumption that for bosh the default storage account is always the oldest, aka I can get one created and then add the blob storage account?

You can try the following steps:
1. Create a general-purpose storage account with two containers `bosh` and `stemcell`.
2. Create a blob storage account with the container `buildpacks` and so on.
3. Use the storage account name in step 1 as the default storage account when deploying bosh. Specify the properties `storage_account_name` and `use_managed_disks` in CPI global configurations.
    ```
    azure:
      storage_account_name: <your-default-storage-account>
      use_managed_disks: true
    ```
4. Deploy BOSH.
5. Deploy CF using the storage account in step 2 as the blobstore.

**Comment by bingosummer** [comment]
@schmidtsv , will the steps help?

**Comment by bingosummer** [comment]
Closing as stale, feel free to mention us and have it re-opened.
