### ISSUE TITLE
Enable IP forwarding fo a VM's NIC using Bosh

### ISSUE THREAD

**Issue by firasnajjar** [cloudfoundry-incubator/bosh-azure-cpi-release#379]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: any
BOSH     Version: any
CF       Version:
Diego    Version:

### Stemcell
Version: any
Distro:
  - [x] Ubuntu
  - [x] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details
This is a feature request not a bug or issue with the CPI.
Currently, there is no way using the Azure Bosh CPI to enable IP forwarding in the IP configuration of the NIC for a machine created via Bosh. It would be great if you can support such a feature. There could be a cloud property ip_forwarding for example that can be added as vm extension in cloud-config and attached to an instance group. This will enable/disable IP forwarding on the nic of this VM.

This is currently supported in the CPI of GCP. You can find the documentation here: 
 https://bosh.io/docs/google-cpi.html#vm-types

It will be great if Azure CPI can offer simillar functionality.

**Comment by bingosummer** [comment]
Thanks @firasnajjar for raising the feature request. Just want to let you know that we will evaluate it and keep you posted.

**Comment by bingosummer** [comment]
Updates: We are working on the codes.
https://github.com/bingosummer/bosh-azure-cpi-release/commits/ip-forwarding
