### ISSUE TITLE
Reuse uploaded stemcell for all tests to speed up lifecycle tests

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#43]
Multiple log lines `create_page_blob: blob_name: bosh-stemcell-*` found in https://bosh-azure-cpi.ci.cf-app.com/pipelines/azure-cpi/jobs/lifecycle/builds/7

**Comment by AbelHu** [comment]
Fix it in this commit https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/commit/e1c1d77cd97d789231c7f087936e44fb9fffd121
