### ISSUE TITLE
Error using Azure Template

### ISSUE THREAD

**Issue by cbrianball** [cloudfoundry-incubator/bosh-azure-cpi-release#46]
I'm trying to deploy Cloud Foundry. I'm on the step where I'm creating Azure resources using ARM templates. I click on the Deploy To Azure link on [this page](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/deploy-bosh-using-arm-templates.md).

Once I fill in the parameters, it runs for a while, and then errors on the initdevbox step with the below error:

```json
{
   "status":"Failed",
   "error":{
      "code":"ResourceDeploymentFailure",
      "message":"The resource operation completed with terminal provisioning state 'Failed'.",
      "details":[
         {
            "code":"VMExtensionProvisioningError",
            "message":"VM has reported a failure when processing extension 'initdevbox'. Error message: \"Script returned an error.\n---stdout---\n2015/11/10 18:08:35 }\n\n---errout---\nw.githubusercontent.com)|199.27.76.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 3721 (3.6K) [text/plain]\nSaving to: 'bosh.yml'\n\n     0K ...                                                   100%  670M=0s\n\n2015-11-10 18:08:34 (670 MB/s) - 'bosh.yml' saved [3721/3721]\n\n--2015-11-10 18:08:34--  https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/bosh-setup//setup_dns.py\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.76.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.76.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 7406 (7.2K) [text/plain]\nSaving to: 'setup_dns.py'\n\n     0K .......                                               100% 1.25G=0s\n\n2015-11-10 18:08:34 (1.25 GB/s) - 'setup_dns.py' saved [7406/7406]\n\n--2015-11-10 18:08:34--  https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/bosh-setup//create_cert.sh\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.76.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.76.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 204 [text/plain]\nSaving to: 'create_cert.sh'\n\n     0K                                                       100% 40.5M=0s\n\n2015-11-10 18:08:34 (40.5 MB/s) - 'create_cert.sh' saved [204/204]\n\n--2015-11-10 18:08:34--  https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/bosh-setup//setup_devbox.py\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.76.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.76.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 4034 (3.9K) [text/plain]\nSaving to: 'setup_devbox.py'\n\n     0K ...                                                   100%  726M=0s\n\n2015-11-10 18:08:34 (726 MB/s) - 'setup_devbox.py' saved [4034/4034]\n\n--2015-11-10 18:08:34--  https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/bosh-setup//init.sh\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.76.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.76.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 1024 (1.0K) [text/plain]\nSaving to: 'init.sh'\n\n     0K .                                                     100%  212M=0s\n\n2015-11-10 18:08:34 (212 MB/s) - 'init.sh' saved [1024/1024]\n\n--2015-11-10 18:08:34--  https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/bosh-setup//deploy_bosh.sh\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.76.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.76.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 110 [text/plain]\nSaving to: 'deploy_bosh.sh'\n\n     0K                                                       100% 25.0M=0s\n\n2015-11-10 18:08:34 (25.0 MB/s) - 'deploy_bosh.sh' saved [110/110]\n\n--2015-11-10 18:08:34--  https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/bosh-setup//98-msft-love-cf\nResolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.76.133\nConnecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.76.133|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 407 [text/plain]\nSaving to: '98-msft-love-cf'\n\n     0K                                                       100% 86.3M=0s\n\n2015-11-10 18:08:35 (86.3 MB/s) - '98-msft-love-cf' saved [407/407]\n\nTraceback (most recent call last):\n  File \"setup_devbox.py\", line 31, in <module>\n    blob_service.create_container('bosh')\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.2.2.0/azure/storage/blobservice.py\", line 190, in create_container\n    _dont_fail_on_exist(ex)\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.2.2.0/azure/__init__.py\", line 891, in _dont_fail_on_exist\n    raise error\nazure.WindowsAzureError\n\n\"."
         }
      ]
   }
}
```

Is there something wrong with the template or might it be something I'm not doing right when setting values for the template?

**Comment by bingosummer** [comment]
Hi @cbrianball . Thanks for your feedback.

The initdevbox step threw a WindowsAzureError when it tried to create a container `bosh` in your storage account.
Could you check your settings for the template, and re-deploy it?
If it does not work for you, please feel free to let us know.

**Comment by cbrianball** [comment]
I had tried 2 - 3 times and kept getting the same error. I tried again, but since you pointed out the storage account, I used a different name (this time with all lower case) and it worked.

Clearly I failed to read the description for the storage account name on the page I referenced where it states lower case letters and numbers only.

So to me it seems that Azure should have returned an error when the storage account create request was issued and it shouldn't have even made it as far as it did.

Thanks, I'll close this issue.

**Comment by bingosummer** [comment]
Totally agree with you, @cbrianball . I will try to figure out why Azure does not return an error when the storage account name is invalid. Will let you know the result.

Thanks.

**Comment by vcherukuri** [comment]
I tried deploying pivotal cloud foundry on Azure. After deploying few resources , it failed with an error. I dont see a problem with Storage account as it is created properly. 
STATUSConflict
PROVISIONING STATEFailed
TIMESTAMP6/24/2016, 4:24:48 PM
DURATIONPT29M54.6658648S
TYPEMicrosoft.Compute/virtualMachines/extensions
RESOURCE ID/subscriptions/7eab3893-bd71-4690-84a5-47624df0b0e5/resourceGroups/PivotalCloudFoundry/providers/Microsoft.Compute/virtualMachines/myjumpboxnpvfpqoisk5zk/extensions/initdevbox
STATUSMESSAGE{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'initdevbox'. Error message: \"Script returned an error.\n---stdout---\nDownload complete.\nCurrent working dir : /var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0\nSys.Path: ['/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl', '/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl', '/usr/share/python-wheels/six-1.5.2-py2.py3-none-any.whl', '/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl', '/usr/share/python-wheels/colorama-0.2.5-py2.py3-none-any.whl', '/usr/share/python-wheels/pip-1.5.4-py2.py3-none-any.whl', '/usr/share/python-wheels/chardet-2.2.1-py2.py3-none-any.whl', '/usr/share/python-wheels/html5lib-0.999-py2.py3-none-any.whl', '/usr/share/python-wheels/distlib-0.1.8-py2.py3-none-any.whl', '/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/download/0', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '']\n\n---errout---\n\rExtracting templates from packages: 32%\rExtracting templates from packages: 64%\rExtracting templates from packages: 96%\rExtracting templates from packages: 100%\nTraceback (most recent call last):\n  File \"./bootstrap.py\", line 159, in <module>\n    check_quota(subscription_id, tenant, client_id, client_secret, location, numofcores)\n  File \"./bootstrap.py\", line 52, in check_quota\n    usage_paged=compute_client.usage.list(location).usages\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/azure/mgmt/compute/computemanagement.py\", line 3889, in list\n    raise error\nazure.common.AzureHttpError: {\"error\":{\"code\":\"AuthorizationFailed\",\"message\":\"The client '1f5db171-dcf1-4d63-9fed-131e165ecefa' with object id '1f5db171-dcf1-4d63-9fed-131e165ecefa' does not have authorization to perform action 'Microsoft.Compute/locations/usages/read' over scope '/subscriptions/7eab3893-bd71-4690-84a5-47624df0b0e5'.\"}}\n\n\"."
      }
    ]
  }
}
RESOURCEmyjumpboxnpvfpqoisk5zk/initdevbox

Thanks in advance

**Comment by bingosummer** [comment]
@vcherukuri 
Your issue is about the authorization of your service principal. You need to check the authorization. Do you assign the right role to your service principal?

```
{\"error\":{\"code\":\"AuthorizationFailed\",\"message\":\"The client '1f5db171-dcf1-4d63-9fed-131e165ecefa' with object id '1f5db171-dcf1-4d63-9fed-131e165ecefa' does not have authorization to perform action 'Microsoft.Compute/locations/usages/read' over scope '/subscriptions/7eab3893-bd71-4690-84a5-47624df0b0e5'.\"}
```
