### ISSUE TITLE
Deploy BOSH failed

### ISSUE THREAD

**Issue by ritazh** [cloudfoundry-incubator/bosh-azure-cpi-release#49]
Error in the log:

Command 'deploy' failed:
  creating stemcell (bosh-azure-hyperv-ubuntu-trusty-go_agent 0000):
    CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"http_get_response - get_token - http error: 400\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:842:in `get_token'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:861:in `http_get_response'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1013:in `http_post'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:792:in `get_storage_account_keys_by_name'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:13:in `initialize'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:367:in `new'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:367:in `init_azure'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:19:in `initialize'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/bin/azure_cpi:26:in `new'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/bin/azure_cpi:26:in `block in \u003cmain\u003e'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:70:in `call'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:70:in `run'\n/home/ritacfcasestudyvmadmin/.bosh_init/installations/beacefe0-7d5e-4da2-6639-445160a29cd5/packages/bosh_azure_cpi/bin/azure_cpi:34:in `\u003cmain\u003e'","ok_to_retry":false}

**Comment by bingosummer** [comment]
@ritazh It seems that your service principal (tenant_id, client_id, client_secret) is invalid. You can verify it with the following operations:

1. Use Azure CLI to login with your service principal. If you can not login, then the service principal is invalid.
2. Verify that the subscription which the service principal belongs to is the same subscription which is used to create your resource group. (This may happen when you have multiple subscriptions)

**Comment by ritazh** [comment]
@bingosummer Thanks for the reply. I just verified that the service principal is valid and the subscription is the same for the resource group.

**Comment by ritazh** [comment]
Closing this as the issue was caused by a bad `tenant_id` passed into the template.

**Comment by mdcarlson** [comment]
In case others run across this issue, I received this error when attempting to use a newly created free trial account without first creating a new user in Active Directory.   Instructions [here](https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-work-id-from-personal/).  Be sure to use the subscription ID from the new user and not the one from the initial free trial account.

**Comment by techiechap** [comment]
I have ran into issue while deploying the bosh, i get an error 
./deploy_bosh.sh: line 44: unexpected EOF while looking for matching `"'
  1 #!/usr/bin/env bash
  2
  3 set -e
  4
  5 export BOSH_LOG_LEVEL="debug"
  6 export BOSH_LOG_PATH="./run.log"
  7
  8 bosh create-env ~/example_manifests/bosh.yml \
  9   --state=state.json \
 10   --vars-store=~/bosh-deployment-vars.yml \
 11   -o ~/example_manifests/cpi.yml \
 12   -o ~/example_manifests/use-location.yml \
 13   -o ~/example_manifests/custom-cpi-release.yml \
 14   -o ~/example_manifests/custom-environment.yml \
 15   -o ~/example_manifests/use-azure-dns.yml \
 16   -o ~/example_manifests/jumpbox-user.yml \
 17   -o ~/example_manifests/keep-failed-or-unreachable-vms.yml \
 18   -o ~/example_manifests/uaa.yml \
 19   -o ~/example_manifests/credhub.yml \
 20   -v director_name=azure \
 21   -v internal_cidr=10.0.0.0/24 \
 22   -v internal_gw=10.0.0.1 \
 23   -v internal_ip=10.0.0.4 \
 24   -v cpi_release_url=https://bosh.io/d/github.com/cloudfoundry/bosh-azure-cpi-release?v=35.5.0 \
 25   -v cpi_release_sha1=faebe370c143554fe471c3f6aafb523ab48c43ea \
 26   -v director_vm_instance_type=Standard_D2_v2 \
 27   -v resource_group_name=cloudfoundry-RG \
 28   -v location=northcentralus \
 29   -v vnet_name=boshvnet-crp \
 30   -v subnet_name=Bosh \
 31   -v default_security_group=nsg-bosh \
 32   -v environment=AzureCloud \
 33   -v subscription_id=ff4a3686-825b-43a2-9117-f52a640a8ceb \
 34   -v tenant_id=6ad26772-c556-42f4-9a4a-35d46f49433e \
 35   -v client_id=b9b5d699-81a1-40e7-98aa-b99436ff2d8b \
 36   -v client_secret=""6e28b41b-9bca-40c7-b26e-01879c53c786" \
 37   -o ~/example_manifests/use-managed-disks.yml
 38
 39 cat >> "/home/dcadmin/.profile" << EndOfFile
 40 # BOSH CLI
 41 export BOSH_ENVIRONMENT=10.0.0.4
 42 export BOSH_CLIENT=admin
 43 export BOSH_CLIENT_SECRET="$(bosh int ~/bosh-deployment-vars.yml --path /admin_password)"
 44 export BOSH_CA_CERT="$(bosh int ~/bosh-deployment-vars.yml --path /director_ssl/ca)"
 45 EndOfFile
 46 source /home/dcadmin/.profile

**Comment by bingosummer** [comment]
@techiechap `-v client_secret=""6e28b41b-9bca-40c7-b26e-01879c53c786" ` this line has an extra `"`.

Additionally, if the `client_secret` is your real service principal secret, you should not post it in github without redacting it. You may want to reset your secret.

**Comment by techiechap** [comment]
My bad, I have deleted the SP, yes will try to spin it again
