### ISSUE TITLE
Director couldn't be targeted after VM restart

### ISSUE THREAD

**Issue by tintoverano** [cloudfoundry-incubator/bosh-azure-cpi-release#55]
hello,

following a successful bosh deploy I stopped and restarted the bosh vm, but Director was not reachable at 10.0.0.4

I tried to figure out how this could be mended, but finally resorted to redeploying bosh and Director works again

is there a way to ensure that stopping the bosh vm doesn't effect the bosh environment?

thanks,

Zoli

**Comment by AbelHu** [comment]
It is by BOSH design. 
BOSH expects that machines that were stopped outside of its control will be brought up through BOSH, either automatically via resurrector or manually via bosh cck/recreate. 
You can reference this issue [#956] (https://github.com/cloudfoundry/bosh/issues/956)

**Comment by tintoverano** [comment]
I see, thank you.
