### ISSUE TITLE
setting compilation worker numbers has no impact on deployment process

### ISSUE THREAD

**Issue by tintoverano** [cloudfoundry-incubator/bosh-azure-cpi-release#57]
hello,

while deploying cloud foundry using this setting (because of free tier core usage limitations: use 4 workers instead of 6):

````
compilation:
  workers: 4
  network: cf_private
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: Standard_D1
````

I did a redeploy after changing the manifest yml as above:

````
bosh deploy --recreate
````

I still get the following error:

````
Error 100: http_put - error: 409 message: {
  "error": {
    "code": "OperationNotAllowed",
    "message": "Operation results in exceeding quota limits of Core. Maximum allowed: 4, Current in use: 4, Additional requested: 1."
  }
}
````

what do you suggest I should do?

thanks,

zoltán

**Comment by AbelHu** [comment]
It seems like that your maximum allowed cores is 4. You can use 1 worker for compilation. Or you can increase the maximum core count  in your account.

**Comment by tintoverano** [comment]
hi,

I've already changed the manifest to use 4 workers instead of 6 and it had no effect, see above

I'll set using 1 worker in the manifest

is it ok to use "--recreate" or should I use some other command to redo deployment?

thanks

**Comment by tintoverano** [comment]
compilation went down fine using 1 worker :+1:

**Comment by xchen20** [comment]
which specific file should I locate to overwrite the number of worker ?

**Comment by xchen20** [comment]
not really helpful in my case, I'm using 1 worker, but still got the same error

**Comment by arungithub9** [comment]
> 
> 
> which specific file should I locate to overwrite the number of worker ?

Could you please tell me which file it is

**Comment by AbelHu** [comment]
Please reference the solution here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-resource-quota

**Comment by arungithub9** [comment]
Hi thanks for the reply, what series of cpu must I choose for the request. there are a lot here https://imgur.com/a/fArT7It ... which is the default one ? Is it Av2 or eav4 or something else? Thank you again.

**Comment by AbelHu** [comment]
It depends on which type of VMs you want to use. Please reference https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general
