### ISSUE TITLE
What should I do next?

### ISSUE THREAD

**Issue by nnasaki** [cloudfoundry-incubator/bosh-azure-cpi-release#59]
I have deployed [Cloud Foundry on Azure](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/deploy-cloudfoundry.md). I am trying to [Getting Started with the cf CLI]( https://docs.cloudfoundry.org/devguide/installcf/whats-new-v6.html). However, I can't found API endpoint...  What should I do?

**Comment by bingosummer** [comment]
@nnasaki 
The API endpoint is `https://api.YOUR-SYSTEM-DOMAIN`.
If you use the example manifest, you can find the `YOUR-SYSTEM-DOMAIN` is set as `cf.azurelovecf.com`.
So, you should login with `cf login -a https://api.cf.azurelovecf.com --skip-ssl-validation`.

**Comment by tintoverano** [comment]
hi @bingosummer 

is there a way to check that the system domain is the one above? I don't seem to find this setting on the portal

thanks,

zoltán

**Comment by bingosummer** [comment]
Hi @nnasaki 
You can search `system_domain` in `single-vm-cf-224.yml` or `multiple-vm-cf-224.yml`.

**Comment by tintoverano** [comment]
I meant after deployment of cf

thanks

**Comment by bingosummer** [comment]
Yes. When you deploy CF, you need to prepare a manifest `single-vm-cf-224.yml`. Right?
In the yml file, you need to configure `system_domain`.
In our example manifest, we set `system_domain` as the default value `cf.azurelovecf.com`.
You can change it into any domain name you owns.
After the deployment, you should login with the endpoint `https://api.system_domain`.

**Comment by tintoverano** [comment]
I see, OK
thanks!!

**Comment by bingosummer** [comment]
@tintoverano :)

**Comment by tintoverano** [comment]
@bingosummer
I created a custom subdomain to use for cf
can I use this now by changing the manifest and redeploy cf or there are other ways?
thanks a lot

**Comment by bingosummer** [comment]
Yes.
1. `sudo python setup_dns.py -d <your-custom-domain> -i 10.0.16.4 -e <reserved-ip-for-cloud-foundry> -n <public-ip-of-dev-box>`.
2. Verify it with the `dig api.<your-custom-domain>` command.
3. Change the manifest and redeploy cf.
4. Login with `cf login -a https://api.<your-custom-domain> --skip-ssl-validation`.

**Comment by tintoverano** [comment]
@bingosummer  
I got to step 4 with success, but then

````
API endpoint: https://api.cp.protact.me
FAILED
Error performing request: Get https://api.cp.protact.me/v2/info: dial tcp 40.115.3.184:443: getsockopt: connection refused
````

I guess it is probably some inbound rule problem

I have set up based on the AWS docs the following inbound rules for devbox (the IP above), I couldn't find docs for Azure (any hint?)

![image](https://cloud.githubusercontent.com/assets/8960294/11763022/5a11ab48-a0fa-11e5-9a1d-4f8a5bf1fae9.png)

what do you think I'm missing?

thanks again

**Comment by bingosummer** [comment]
@tintoverano 
It seems that you bind your domain name to the IP of the devbox. (The public IP `xxx-devbox` in Azure Portal)
Instead, you should bind it to the IP of the Cloud Foundry VM. (The public IP `xxx-cf` in Azure Portal).
For the public IP of Cloud Foundry VM, the rules have been setup in your manifest. (https://github.com/bingosummer/bosh-azure-cpi-release/blob/refine-docs/docs/example_manifests/single-vm-cf-224.yml#L27)

For test, I suggest that you can use `cf login -a https://<public-ip-of-cloudfoundry-vm>.xip.io --skip-ssl-validation`. In this way, you don't need to setup anything about DNS.
For production, you need to configure a DNS for your domain name. We are preparing a guidance about how to setup the DNS. Will let you know after it's ready.

**Comment by tintoverano** [comment]
@bingosummer 

thanks a lot for your support!!

I'm puttting together a prototype and need to explore all aspects, that's why I'd like to use a real DNS

checked the DNS at step 1 above and you are right current settings does point to the devbox's IP:

````
; <<>> DiG 9.9.5-3ubuntu0.5-Ubuntu <<>> api.cp.protact.me
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 54758
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;api.cp.protact.me.		IN	A

;; AUTHORITY SECTION:
protact.me.		604800	IN	SOA	ns.protact.me. root.protact.me. 1 604800 86400 2419200 604800

;; Query time: 1 msec
;; SERVER: 10.0.0.100#53(10.0.0.100)
;; WHEN: Sun Dec 13 09:18:53 UTC 2015
;; MSG SIZE  rcvd: 90
````


this is what I have/had in the manifest the last time I deployed cf:

````
  networks:
  - name: reserved
    static_ips: 40.115.54.213 # <--- Replace with your reserved public IP address for cloud foundry
  - name: cf_private
    default: [gateway, dns]
    static_ips: [10.0.16.4]
````


and I just reset the DNS at my provider and from my place it looks like this now:

````
tintoverano@tintodev:~$ nslookup protact.me
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	protact.me
Address: 40.115.54.213
````

it points to cf's public IP at Azure

do I need to flush DNS or else?

**Comment by bingosummer** [comment]
@tintoverano 
If `40.115.54.213` is as same as `cf-ip` in `~/settings`, your configuration is right.
It should work.

Could I have a permission to logon your devbox to troubleshoot the issue?
Please email binxi@microsoft.com to share the credentials if you are fine with it.

**Comment by bingosummer** [comment]
@nnasaki Do you find the API endpoint? Hope my answer helps.
If it does not work, feel free to let me know.

**Comment by tintoverano** [comment]
@bingosummer 
sending my credentials...
thanks

**Comment by nnasaki** [comment]
@bingosummer Thank you for support. I found the API endpoint! But, I have a another problem. I could not login cf. What should I use credential?

```
nnasaki@ncloudfoundry:~$ cf login -a https://api.cf.azurelovecf.com --skip-ssl-validation
API endpoint: https://api.cf.azurelovecf.com

Email> nnasaki@ncloudfoundry.onmicrosoft.com

Password> 
Authenticating...
Credentials were rejected, please try again.

Password> 
Authenticating...
Credentials were rejected, please try again.

Password> 
Authenticating...
Credentials were rejected, please try again.
FAILED
Unable to authenticate.

                   
API endpoint:   https://api.cf.azurelovecf.com (API version: 2.42.0)   
Not logged in. Use 'cf login' to log in.
```

**Comment by bingosummer** [comment]
@nnasaki 
The Email and Password should be `admin` and `c1oudc0w` if you don't change the manifest.

**Comment by nnasaki** [comment]
@bingosummer aha! I get it! Thanks! I keep trying cf.

**Comment by bingosummer** [comment]
Have helped @tintoverano setup DNS offline. It works now.
@nnasaki can login CF now.
Please close this issue.

**Comment by nnasaki** [comment]
Alright. Thank you very much.
