### ISSUE TITLE
unable to access ci: ssl cert revoked error

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/bosh-azure-cpi-release#62]
Hi,

I'm experiencing "sec_error_revoked_certificate" error (FF) when trying to connect to https://bosh-azure-cpi.ci.cf-app.com/  and "NET::ERR_CERT_REVOKED" (chrome).

Both with Firefox 43.0 and chrome 47.0.2526.106 m running windows 7 with standard built-in consummer certs.

Is there an available workaround ? Started looking at blog post, but did not seem obvious yet.
https://productforums.google.com/forum/?hl=en#!topic/chrome/4P2O3M0zGfg

Thanks in advance,

Guillaume.

**Comment by AbelHu** [comment]
It is very weird. I also hit the issue before. When I hit it, I can access it with IE or with another machine. After I reinstall my computer for other reason, I do not hit this issue again. 
You can try to access it with IE.

**Comment by cppforlife** [comment]
@gberche-orange are you still seeing this issue? i cannot reproduce it. chrome shows green lock for https for me.

**Comment by gberche-orange** [comment]
@cppforlife 

I'm still reproducing today with Firefox 43.0.2 windows, but not with chromium 44.0.2379.0

FF error (sorry in french):

``Une erreur est survenue pendant une connexion à bosh-azure-cpi.ci.cf-app.com. Le certificat du pair a été révoqué. (Code d'erreur : sec_error_revoked_certificate)``

**Comment by cppforlife** [comment]
I think that was fixed some time ago.
