### ISSUE TITLE
CID of VMs is not well named

### ISSUE THREAD

**Issue by supertopher** [cloudfoundry-incubator/bosh-azure-cpi-release#68]
Currently the helper for generate_instance_id (azure/helpers.rb:56) uses the storage account name as the base name for the VM name.  This creates confusion while searching for both storage and VMs by polluting the namespace with the same string across both.  

We would prefer that the VMs simply had the UUID without the storage account name.  It does not add value to understanding and clouds search results.

**Comment by AbelHu** [comment]
Thanks for your feedback, @supertopher. Currently Azure CPI needs to parse the storage account name from the VM name so that we cannot remove it.

**Comment by landesherr** [comment]
@AbelHu thanks for responding so quickly! Would it be plausible to move this storage account name to the end of the string for UUID?  When viewing the VMs over the web (or really in any format that would truncate a string) all the VMs appear to be the same.  IE: the first 32 characters are always `Storage-account-name-1010......` If we reversed the order we could at least identify the UUID we are looking over.

**Comment by AbelHu** [comment]
@landesherr It is a good idea. But this change may impact all users who have used current Azure CPI. We will consider to update it later.

**Comment by landesherr** [comment]
@AbelHu I'm trying to imagine how this could impact the end users of the current CPI implementation, since the CPI version is always explicitly set in the manifest. Are you concerned about users who may be trying to parse the output programmatically, or is there some other specific concern?

Thanks for your quick responses, by the way. We appreciate your help in this matter.

**Comment by AbelHu** [comment]
@landesherr We need to consider how to handle the CPI version upgrade. If someone uses the new CPI in current deployment, the current disk name cannot be parsed correctly and errors will occur. We will have a big change later which is also related to disks. So let us do it once.
