### ISSUE TITLE
Azure CPI reports "disk named XXX already exists" when trying to re-attach disk.

### ISSUE THREAD

**Issue by landesherr** [cloudfoundry-incubator/bosh-azure-cpi-release#73]
When running a bosh cloudcheck and an unattached disk is found, attempting to remediate the situation by re-attaching the disk results in the nonsensical error "A disk named 'XXX' already exists", where XXX is the name of the identified disk. This operation *should not* entail the creation of a new disk.

Example Incident:
```
Performing cloud check...

Director task 304
  Started scanning 4 vms
  Started scanning 4 vms > Checking VM states. Done (00:00:10)
  Started scanning 4 vms > 4 OK, 0 unresponsive, 0 missing, 0 unbound, 0 out of sync. Done (00:00:00)
     Done scanning 4 vms (00:00:10)

  Started scanning 3 persistent disks
  Started scanning 3 persistent disks > Looking for inactive disks. Done (00:00:18)
  Started scanning 3 persistent disks > 2 OK, 0 missing, 0 inactive, 1 mount-info mismatch. Done (00:00:00)
     Done scanning 3 persistent disks (00:00:18)

Task 304 done

Started		2016-01-05 18:06:40 UTC
Finished	2016-01-05 18:07:08 UTC
Duration	00:00:28

Scan is complete, checking if any problems found...

Found 1 problem

Problem 1 of 1: Inconsistent mount information:
Record shows that disk '[REDACTED]' should be mounted on [REDACTED].
However it is currently :
	Not mounted in any VM.
  1. Ignore
  2. Reattach disk to instance
  3. Reattach disk and reboot instance
Please choose a resolution [1 - 3]: 3

Below is the list of resolutions you've provided
Please make sure everything is fine and confirm your changes

  1. Inconsistent mount information:
Record shows that disk '[REDACTED]' should be mounted on [REDACTED].
However it is currently :
	Not mounted in any VM
     Reattach disk and reboot instance

Apply resolutions? (type 'yes' to continue): yes
Applying resolutions...

Director task 305
  Started applying problem resolutions > mount_info_mismatch 12: Reattach disk and reboot instance. Failed: Unknown CPI error 'Bosh::AzureCloud::AzureError' with message 'http_put - error: 400 message: {
  "error": {
    "code": "InvalidParameter",
    "target": "dataDisk.name",
    "message": "A disk named '[REDACTED]' already exists."
  }
}' (00:00:03)

Task 305 done
```

**Comment by sedouard** [comment]
I believe this an active reliability issue we are investigating with the Azure Disk API. It is known that sometimes a Disk API will report disk attach information that is inconsistent with what the Linux VM will report.

A few other partners are hitting this at the moment and it has been escalated to azure engineering.

**Comment by AbelHu** [comment]
@landesherr What had you done before this occurred?
Could you provide logs for advanced investigation?
Use 'bosh ssh' to the VM, collect all logs under /var/vcap/sys/log, /var/vcap/bosh/log, /var/log/. And use 'sudo mount' to check whether the disk is mounted or not.

**Comment by landesherr** [comment]
It appears that the VM in question has been deleted since the incident occurred, likely as part of a redeployment.

The context of the incident was an attempt to rerun a bosh deployment that failed part of the way through. Prior to the incident, we were having issues with deployments failing due to a lag in deleting instances where Azure CPI would report to bosh that an instance was deleted, but the delete was actually not yet complete. Bosh would attempt to create a new instance bound to the IP address held by the supposedly deleted VM, and would fail to do so.

Re-deploying would eventually work, but the disk-related incident in question required manual intervention to fix.

**Comment by AbelHu** [comment]
@landesherr I see. Why did you run 'bosh cloudcheck"? what happened before this? If you can share your manifests and scenarios, We can try to repro it and find what happens. My email is chou.hu@microsoft.com.

**Comment by AbelHu** [comment]
No logs for investigation. Close it for now. Please reactive it if you can repro and share logs.
