### ISSUE TITLE
Bosh failed to create VM (Error random and flaky)

### ISSUE THREAD

**Issue by datianshi** [cloudfoundry-incubator/bosh-azure-cpi-release#84]
When using bosh deploy .

I got Error 450002: Timed out pinging to c6f09e6a-2ff1-42f0-bd2e-3d98e6574d34 after 600 seconds

This errors comes with a significant chance. It is kind of more than 40% for me (Unluck!!!!), while sometimes succeed. 
When it happened, I looked at the azure portal. All the vnet, subnets and IPs are placed correctly, as well as no azure error logs happened. Ping this VM from the internal network (A jump host on the same subnet) does not work. Ironically, if the failed VM has a VIP, I can ssh into it through the public VIP, however the network inside of failed VM can not route through the subnet gateway. Guess subnet gateway failed on the bosh deployed VM is causing timeout. 

Any thoughts whether the bosh side could cause the problem? Or it is just flaky Microsoft Azure network?

stemcell 3163, CPI release 6, bosh release 250

**Comment by AbelHu** [comment]
Thank you for reporting it. It is a known network issue. Which region are you using? You can try to use East US.

**Comment by datianshi** [comment]
I am in Central US

**Comment by AbelHu** [comment]
Before Central US is patched, you can try it on East US. After Central US is ready, we will update you.

**Comment by datianshi** [comment]
Thanks @AbelHu What regions currently are patched and agnostic of this issue? When you are saying patch? Is this going to happen on azure side or bosh CPI side?

**Comment by svrc-pivotal** [comment]
same problem on West US.

**Comment by AbelHu** [comment]
Pleaee try it in east us.

Best Regards,
Abel HU

? 2016?2?1??19:13?Stu Charlton <notifications@github.com<mailto:notifications@github.com>> ???


same problem on West US.

-

**Comment by danhigham** [comment]
@AbelHu is this problem specific to the BOSH CPI? or is it just Azure in those regions?

**Comment by AbelHu** [comment]
@danhigham Is it an issue of Azure network. It has been fixed in East US. Other regions will be soon.

**Comment by bingosummer** [comment]
@datianshi and @danhigham 
Any update on this issue?
Please let us know if you hit any problem.
Thanks

**Comment by AbelHu** [comment]
@danhigham @datianshi , This issue has been fixed so I close it.
