### ISSUE TITLE
Can't set bosh target, error message "cannot access director"

### ISSUE THREAD

**Issue by YoBetty** [cloudfoundry-incubator/bosh-azure-cpi-release#87]
I had been trying to do it on the local machine using the private IP address, then from another machine using the public IP address. The problem appears to be that nothing is listening on port 25555. Did something go wrong during bosh deploy?

**Comment by AbelHu** [comment]
What is your environment? Do you follow our guidance to use template to deploy it? If you can your bosh manifest to me (chou.hu@microsoft.com), I can help you to investigate it.

**Comment by YoBetty** [comment]
Yes - it is attached.

Of note - I used the ARB template and the Azure Portal to enter the additional information I generated from creating service principal (client ID and client secret). I did not alter anything else in the manifest file.

I noticed that the private IP address that was created for the bosh vm is 10.0.0.100 while the bosh yml file appears to be looking for 10.0.0.4. Nothing is listening on port 25555 on the bosh vm, which is probably why the director is not running. 

Thanks,
Beth

**Comment by AbelHu** [comment]
@YoBetty I cannot see your any attached file. I guess you cannot attach it when you reply GitHub comments.
10.0.0.100 is the dev-box IP address. 10.0.0.4 is for BOSH director VM. 25555 should be listened in BOSH director VM.
You can send the ~/bosh.yml and ~/run.log to me if you follow our template guidance to deploy it.

**Comment by YoBetty** [comment]
Chou - I'm asking Pivotal on their end as well, but the pertinent error message seems to be that there is "no route to host" over 10.0.0.4:22. My assumption is this probably caused some of the configuration to fail.

**Comment by AbelHu** [comment]
@YoBetty Which datacenter are you testing? We have a known issue about network. After the VM is created, the network is not ready so that you cannot ssh to the VM. Maybe you hit this issue. If so, please try it in east us. This issue is fixed and east us has been patched.

**Comment by YoBetty** [comment]
Ok - thanks for letting me know. It was deployed in US Central.

**Comment by YoBetty** [comment]
That must have been the problem. I installed it in East and it worked. I looked to see if this was reported on the health page and I didn’t see anything. Going forward, how can I tell if it’s a platform issue?

Thanks for your help!!

**Comment by AbelHu** [comment]
@YoBetty Normally we need to check bosh-init logs, task logs and bosh-agent logs to identify whether it is a platform issue. Since this issue has been fixed, close it.
