### ISSUE TITLE
generate.exe failing with "panic: no rep jobs found"

### ISSUE THREAD

**Issue by ngngsoftorg** [cloudfoundry-incubator/bosh-azure-cpi-release#95]
Attempting to push my first cf/diego .net application on azure as described here:
https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/push-your-first-net-application-to-cloud-foundry-on-azure

Completed all prerequisites:
- Bosh created and deployed in azure.
- CF & Diego created and deployed in azure.
- Diego test app bingo app deployed and working.
- Windows subnet created
- WindowsForDiego VM created
- setup.ps1 executed properly.

generate.exe failed with this error:

```
panic: no rep jobs found

goroutine 1 [running]:
main.firstRepJob(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:254 +0x147
main.fillEtcdCluster(0xc082019ee8, 0x0, 0x0, 0x0, 0x0)
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:236 +0x40
main.main()
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:121 +0xc71

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0xc08200e210)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc08200e210)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3
```

install.bat has not been created.  Has anyone seen this before?  Any ideas what it could mean?

Bosh Deployments, Releases, Instances info:

```

+----------+----------------------+-----------------------------------------------+--------------+
| Name     | Release(s)           | Stemcell(s)                                   | Cloud Config |
+----------+----------------------+-----------------------------------------------+--------------+
| cf-azure | cf/224               | bosh-azure-hyperv-ubuntu-trusty-go_agent/3169 | none         |
+----------+----------------------+-----------------------------------------------+--------------+
| cf-diego | cf/224               | bosh-azure-hyperv-ubuntu-trusty-go_agent/3169 | none         |
|          | diego/0.1444.0       |                                               |              |
|          | etcd/20              |                                               |              |
|          | garden-linux/0.330.0 |                                               |              |
+----------+----------------------+-----------------------------------------------+--------------+

+--------------+-----------+-------------+
| Name         | Versions  | Commit Hash |
+--------------+-----------+-------------+
| cf           | 224*      | 65621dd0+   |
| diego        | 0.1444.0* | c5f802c8    |
| etcd         | 20*       | f9cfa965+   |
| garden-linux | 0.330.0*  | a92518a2    |
+--------------+-----------+-------------+
(*) Currently deployed
(+) Uncommitted changes


+----------------------------------------------------+---------+-----+-------------+-----------+
| Instance                                           | State   | AZ  | VM Type     | IPs       |
+----------------------------------------------------+---------+-----+-------------+-----------+
| diego_z1/0 (2cc3653d-fffc-4eb6-8d52-e1bf6906686a)* | running | n/a | resource_z1 | 10.0.32.4 |
+----------------------------------------------------+---------+-----+-------------+-----------+

```

**Comment by AbelHu** [comment]
@ngngsoftorg I am investigating this. Will update you later.

**Comment by ngngsoftorg** [comment]
Thanks.  Let me know if I can give you any logs, etc.

**Comment by AbelHu** [comment]
We reproduced the error. It is a little weird that sometimes it does work. We also had verified it before we published the doc. Need more time to investigate it.

Best Regards,
Abel HU

? 2016?2?26??20:49?Nicholas Grabowski <notifications@github.com<mailto:notifications@github.com>> ???


Thanks. Let me know if I can give you any logs, etc.

-

**Comment by ngngsoftorg** [comment]
ok, interested in seeing a work around.  Thanks.

**Comment by AbelHu** [comment]
@ngngsoftorg We have been investigating this issue. It seems like that BOSH has been changed since our last testing. We need more time to update the manifest and verify the latest version.

**Comment by vikrant3007** [comment]
@AbelHu - Please let us know if you got a chance to resolve this issue or suggest a workaround.

Thanks.

**Comment by AbelHu** [comment]
@vikrant3007 I have regenerated a new manifest with the latest Diego releases. But I have some problems in starting .NET application in my environment. After I fix it, I will send you the new manifest.

**Comment by ngngsoftorg** [comment]
Thanks

**Comment by AbelHu** [comment]
@ngngsoftorg Could you send an email to me chou.hu@microsoft.com? I can send the new manifest to you by email tomorrow.

**Comment by AbelHu** [comment]
@ngngsoftorg @vikrant3007 [The guide for Diego](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/deploy-diego) has been updated.
