### ISSUE TITLE
Load balancer/VIP configurable of IdleTimeoutInMinutes

### ISSUE THREAD

**Issue by datianshi** [cloudfoundry-incubator/bosh-azure-cpi-release#99]
https://azure.microsoft.com/en-us/blog/new-configurable-idle-timeout-for-azure-load-balancer/

The default of load balancer of idelTimeoutInMinutes seems too low as only 4 minutes.
Like HA proxy default is 900 as 15 minutes, this would cause the problem of connection dropped. 
Can we make this configurable 

Like 
- name: public
  type: vip
  cloud_properties:
     timeout: 900

**Comment by AbelHu** [comment]
It is a good idea. But in next release, CPI will assign the public IP address to the VM directly if VIP is set. If you want to bind a load balancer to a VM, you can create the load balancer in Azure portal or by Azure CLI and then specify the LB name in the manifest.

**Comment by AbelHu** [comment]
@datianshi CPI removes LB and assign public IP directly to VM in this PR #107.
